### ISSUE TITLE
Add support for SolidCache

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-ruby#1003]
[SolidCache](https://github.com/rails/solid_cache) is released.

Related issue about query sanitization: https://github.com/appsignal/support/issues/287

## To do

- [x] Add a test setup using SolidCache
- [x] Fetch an example query
- [x] ~~Fix SolidCache queries sanitization in `sql-lexer`~~
- [x] ~~Add an integration for its features if possible.~~
- [x] [Blog post](https://github.com/appsignal/appsignal-nextjs-blog/issues/1080)

**Comment by unflxw** [comment]
Closing; blog post issue at https://github.com/appsignal/appsignal-nextjs-blog/issues/1080
