### ISSUE TITLE
Log not being rotated

### ISSUE THREAD

**Issue by Amnesthesia** [appsignal/appsignal-ruby#1029]
If your bug is about how AppSignal works in your app specifically we recommend you contact us at support@appsignal.com with your bug report instead.

---

## Describe the bug

`log/appsignal.log` grows forever until containers run out of space, it looks like `Appsignal.logger#logdev` has a max size of 10Mb, but because it doesn't have a max age set, the size is never being checked and the log isn't being rotated (https://github.com/ruby/logger/blob/master/lib/logger/log_device.rb#L128) 

<img width="759" alt="Screenshot 2024-01-16 at 09 26 54" src="https://github.com/appsignal/appsignal-ruby/assets/3265008/62596a39-445c-4427-88ed-1880b256d496">

Logger has `shift_size` set and should be rotating:
<img width="720" alt="Screenshot 2024-01-16 at 09 32 01" src="https://github.com/appsignal/appsignal-ruby/assets/3265008/4b091803-33c1-4ca2-8523-60862974ed36">

## To Reproduce

- AppSignal for Ruby gem version 3.5.2
- Rails 7.0.4

We use Semantic Logger, but that shouldn't be relevant since AppSignal logger sets up its own logger. Just let the app run long enough and the log will never be rotated.

**Comment by luismiramirez** [comment]
It seems the integration logger is set to the debug level. Have you configured AppSignal log level to be `trace` or `debug`?

**Comment by Amnesthesia** [comment]
@luismiramirez We use debug log level because we use AppSignal for centralized logging and want debug logging

**Comment by luismiramirez** [comment]
@Amnesthesia I mean the AppSignal log level, which can be set via [this config option](https://docs.appsignal.com/ruby/configuration/options.html#option-log_level). That log level set to debug is only useful for support purposes when something is wrong with the integration. It's a log of how the AppSignal works internally.

If it's not set to debug, it'll usually be a few lines long at most (3 lines per app boot). For log rotation, you can use `logrotate`; we do that ourselves for our applications.

**Comment by tombruijn** [comment]
Let's rename the internal logger `Appsignal.logger` to be `_logger` or `internal_logger` to avoid confusion in the future. We will not enable auto log rotation because our agent also logs to the same file.

**Comment by tombruijn** [comment]
Created an issue for the logger rename to avoid confusion: https://github.com/appsignal/appsignal-ruby/issues/1033

Let us know why you would need the AppSignal internal logger to be set to debug all the time. We do not recommend it.
