### ISSUE TITLE
Add way to skip requests by external monitoring tools

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-ruby#120]
Tools (such as Pingdom) can generate quite a few requests that add up to the plan limit, but don't offer any insights. 

Some kind of way to tell that a transaction can be discarded by the gem would be nice. 

Requested through Intercom: https://app.intercom.io/a/apps/yzor8gyw/inbox/all/conversations/5481377438

**Comment by matsimitsu** [comment]
I'd prefer to create a call that discards the current transaction:

```
Appsignal::Transaction.current.discard
```
Or something like this. At the end of a transaction, instead of processing, it'll be removed. But I'm not sure how this would work on the agent side (are events etc. already processed?)

**Comment by thijsc** [comment]
If you don't call finish the transaction won't be processed and will just be discarded once the GC cleans up the object.

**Comment by jeroenvisser101** [comment]
@thijsc @matsimitsu #124 is green, can you check it out?
