### ISSUE TITLE
`APPSIGNAL_APP_ENV` is not taken into account in Sinatra integration

### ISSUE THREAD

**Issue by cwaider** [appsignal/appsignal-ruby#1213]
## Describe the bug

According to the [documentation](https://docs.appsignal.com/ruby/configuration/options.html#option-appsignal_app_env), the `APPSIGNAL_APP_ENV` environment variable can be used to overwrite environment settings for the runtime environment.
When using the integration for Sinatra, the environment pushed to Appsignal is overwritten by the Sinatra environment. 

`Appsignal.load(:sinatra)` seems to initialize a default config that uses the Sinatra app settings. This is running in a production environment in our example. This default config then seems to overwrite the initial config generated in `Appsignal.start`.

## To Reproduce

- Using AppSignal for Ruby gem version 3.12.1
- In my app using framework Sinatra version 4.0.0
- With this code:
```
require 'appsignal'
require 'sinatra'

Appsignal.load(:sinatra)
Appsignal.start
````

**Comment by tombruijn** [comment]
Fixed in Ruby gem 3.12.2.
