### ISSUE TITLE
Load order dependency for EventFormatter::ViewComponent

### ISSUE THREAD

**Issue by tmaier** [appsignal/appsignal-ruby#1222]
If your bug is about how AppSignal works in your app specifically we recommend you contact us at support@appsignal.com with your bug report instead.

---

## Describe the bug

The gems in my `Gemfile` are mainly ordered alphabetically.
This means `appsignal` is before `view_component`.

```
Appsignal::EventFormatter.formatters
=> {"render_partial.action_view"=>#<Appsignal::EventFormatter::ActionView::RenderFormatter:0x00007ffb6554e788 @root_path="/">,
 "render_template.action_view"=>#<Appsignal::EventFormatter::ActionView::RenderFormatter:0x00007ffb6554e580 @root_path="/">,
 "instantiation.active_record"=>#<Appsignal::EventFormatter::ActiveRecord::InstantiationFormatter:0x00007ffb6554d8b0>,
 "sql.active_record"=>#<Appsignal::EventFormatter::ActiveRecord::SqlFormatter:0x00007ffb6554d0b8>,
 "search.elasticsearch"=>#<Appsignal::EventFormatter::ElasticSearch::SearchFormatter:0x00007ffb6554c6e0>,
 "request.faraday"=>#<Appsignal::EventFormatter::Faraday::RequestFormatter:0x00007ffb6554b7b8>,
 "sql.dry"=>#<Appsignal::EventFormatter::Rom::SqlFormatter:0x00007ffb65549eb8>,
 "sql.sequel"=>#<Appsignal::EventFormatter::Sequel::SqlFormatter:0x00007ffb655492b0>}
 ```
 
 It should be 
 
 ```
 Appsignal::EventFormatter.formatters
=> {"render_partial.action_view"=>#<Appsignal::EventFormatter::ActionView::RenderFormatter:0x00007f7d01fe0328 @root_path="/">,
 "render_template.action_view"=>#<Appsignal::EventFormatter::ActionView::RenderFormatter:0x00007f7d0200fec0 @root_path="/">,
 "instantiation.active_record"=>#<Appsignal::EventFormatter::ActiveRecord::InstantiationFormatter:0x00007f7d0200f7e0>,
 "sql.active_record"=>#<Appsignal::EventFormatter::ActiveRecord::SqlFormatter:0x00007f7d0200ee08>,
 "search.elasticsearch"=>#<Appsignal::EventFormatter::ElasticSearch::SearchFormatter:0x00007f7d0200e278>,
 "request.faraday"=>#<Appsignal::EventFormatter::Faraday::RequestFormatter:0x00007f7d0200daa8>,
 "sql.dry"=>#<Appsignal::EventFormatter::Rom::SqlFormatter:0x00007f7d0200c090>,
 "sql.sequel"=>#<Appsignal::EventFormatter::Sequel::SqlFormatter:0x00007f7d0200b668>,
 "render.view_component"=>#<Appsignal::EventFormatter::ViewComponent::RenderFormatter:0x00007f7d0200aa38 @root_path="/">,
 "!render.view_component"=>#<Appsignal::EventFormatter::ViewComponent::RenderFormatter:0x00007f7d0200a8f8 @root_path="/">}
 ```
 
 Root cause
 
 https://github.com/appsignal/appsignal-ruby/blob/6140c6e88074da4c2ec667909515d04da0b90aff/lib/appsignal/event_formatter/view_component/render_formatter.rb#L24-L33
 
 
This is the only EventFormatter with an if-statement.

**Comment by tombruijn** [comment]
Thanks for the report! We'll have a look to see if we can register the view component using a hook instead (that can check the dependency on `Appsignal.start` rather than `require "appsignal"`).

I see the action view event formatter has the same if-statement, so it might benefit from the same change.

**Comment by tombruijn** [comment]
@tmaier I can't reproduce the issue by moving the the appsignal gem to the top of the Gemfile. If that broke it our railtie (Rails integration) would also not be loaded and don't provide any Rails integration for your app. Are you also not seeing any Rails integration, or is this not a Rails app?

**Comment by unflxw** [comment]
Note that [the ActionView formatter](https://github.com/appsignal/appsignal-ruby/blob/6140c6e88074da4c2ec667909515d04da0b90aff/lib/appsignal/event_formatter/action_view/render_formatter.rb#L26-L35) also has an `if defined?(Rails)` clause -- if this needs to be fixed, it would need to be fixed for both.

**Comment by tmaier** [comment]
Interesting. My application is a rails application. 

> If that broke it, our railtie (Rails integration) would also not be loaded and don't provide any Rails integration for your app.

Rails applications require rails before they require all the other gems in the `Gemfile` via bundler.

See for example https://github.com/railsdiff/rails-new-output/blob/v7.1.3.4/config/application.rb#L3-L7

I created a minimal example to demonstrate it. See https://gist.github.com/tmaier/7cf0b266c35ff605a705b702298cc481

**Comment by unflxw** [comment]
> Rails applications require rails before they require all the other gems in the Gemfile via bundler.

Right, that makes sense -- thanks @tmaier! This explains why the bug manifests for `if defined?(Rails) && defined?(ViewComponent)` but not just for `if defined?(Rails)`. A fix is on the way.

**Comment by unflxw** [comment]
@tmaier AppSignal for Ruby 3.12.4 has been released, with a fix to the issue described in this thread. Thank you for reporting this issue!
