### ISSUE TITLE
Ignore `Sidekiq::JobRetry::Handled` like `Sidekiq::JobRetry::Skip`

### ISSUE THREAD

**Issue by benedikt** [appsignal/appsignal-ruby#1260]
## Describe the bug

With the upgrade to v4.0.2, we started seeing a lot of `Sidekiq::JobRetry::Handled` errors for jobs where we explicitly re-raise an ignored (in our AppSignal config) exception to trigger a retry without reporting an error. I believe `Sidekiq::JobRetry::Handled` could probably be ignored just like `Sidekiq::JobRetry::Skip` in 9ea2d3e83657d115baf166257a50c7e3394318aa because it seems to also be [an internal error of Sidekiq's JobRetry implementation](https://github.com/sidekiq/sidekiq/blob/ed8b217d32f026acc1fae7221dca18d1baa86d11/lib/sidekiq/job_retry.rb#L62-L69).

**Comment by tombruijn** [comment]
Released in Ruby gem 4.0.3!
