### ISSUE TITLE
extconf.rb returns exit code 0 on failure

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#127]
I think extconf.rb should return a failure exit code when it fails to build. Now the automatic build will continue without a working extension.

**Comment by thijsc** [comment]
This by design. Rule nummer one is never break the customer's app/deploy. So the gem still installs, logs the issue and doesn't prevent a deploy from completing.

**Comment by tombruijn** [comment]
Ah so that applies here as well.. Quite annoying to debug, a silent failed install, but I still have to figure out all the moving parts I guess. It could maybe benefit from a message to STDOUT if something goes wrong

**Comment by thijsc** [comment]
There should have been a clear message in appsignal.log. If that wasn't the case I'd consider that a bug. :+1: on warning to stdout during bundle if that's possible.

**Comment by tombruijn** [comment]
The message was in `ext/install.log` and `ext/mkmf.log`, but incomplete clean up of the test files made it look like everything had gone ok until I noticed the agent was running older code.

**Comment by thijsc** [comment]
I think we can close this one now. I've added `mkmf.log` to `appsignal diagnose`, so we can now see this information.
