### ISSUE TITLE
Improving grape on rails docs

### ISSUE THREAD

**Issue by hunterm-wbc** [appsignal/appsignal-ruby#1273]
Hi all,

I'm currently working up updating my app (which runs grape on rails) and it seems like there are some missing configuration steps from the Mounted Grape apps section. I was able to piece together a working setup (still verifying) by finding some notes in the release logs. Here's what I did:

1. Load the grape integration file inside of `app/initializers/appsignal.rb`:
```ruby
# app/initializers/appsignal.rb

Appsignal.load(:grape)
```
2. Update the API classes to use `Appsignal::Rack::GrapeMiddleware` instead of `Appsignal::Grape::Middleware`
```ruby
class FooAPI < Grape::API
  use Appsignal::Rack::GrapeMiddleware
end
```

Please let me know if there is something incorrect here. I'm still working on testing this setup.

**Comment by tombruijn** [comment]
Hi @hunterm-wbc, you're right the Grape middleware constant wasn't updated for Ruby gem 4. I've submitted a PR with the fix. Let us know if you find any other issues :)
