### ISSUE TITLE
Make installation automatable

### ISSUE THREAD

**Issue by LouisKottmann** [appsignal/appsignal-ruby#133]
Hello,

Right now when I run `bundle exec appsignal install $APPSIGNAL_KEY` it asks me a bunch of questions that we'd like Ops to handle and not Devs (especially in the case of many apps).

However `bundle exec appsignal install --help` does not offer an option to do this via flags or environment variables, and reading [install.rb](lib/appsignal/cli/install.rb) I don't think it is possible at all for now.

Would you consider adding flags to the `install` action (or reading env vars, whatever works for you)?

Regards

**Comment by thijsc** [comment]
Hi Louis, thanks for trying AppSignal!

Actually one of the questions the installer asks is wether you'd like to use env vars. If you choose that option it will output a list of env vars you can send to your ops person.

This is just for convenience, AppSignal is fully configurable through the environment. You can find the options here: http://docs.appsignal.com/gem-settings/configuration.html

Does that help?

**Comment by LouisKottmann** [comment]
So if I specify these env vars I don't have to run `bundle exec appsignal install`?

**Comment by thijsc** [comment]
That's correct. The installer is just a convenient way to get a config, using it is optional.

**Comment by LouisKottmann** [comment]
Alright thanks!
