### ISSUE TITLE
[Feature Request] Add API to create check-ins

### ISSUE THREAD

**Issue by d4rky-pl** [appsignal/appsignal-ruby#1338]
Currently Appsignal::CheckIn only supports reporting but there's no easy way to create check-ins programmatically without using the GraphQL API directly. It would be amazing to have an option to call `Appsignal::CheckIn.create`, `.update`, and `.delete` instead of relying on custom code.

Our use case: our application has separate projects for each country in which we operate. We've created a set of custom rake tasks to create (and update/delete) check-ins based on our [clockwork](https://github.com/Rykian/clockwork) configuration instead of creating and updating them manually via UI.

**Comment by d4rky-pl** [comment]
@unflxw I was considering for a moment open sourcing the integration we've built but it was too tied to the way we're doing things and the clockwork gem is no longer maintained in the first place.

With that said, the GraphQL queries we're using:

```ruby
# Fetching list of all check-ins we already have in AppSignal
FETCH_ALL = <<~GRAPHQL
  query {
    organization(slug:"our-org-name") {
      apps {
        id
        name
        notifiers {
          id
        }
        checkIns {
          triggers {
            id
            identifier
            kind
            syntax
            description
            timezone
            waitTimeMinutes
            notifiers {
              id
            }
          }
        }
      }
    }
  }
GRAPHQL
```
```ruby
# Creating a new check-in
CREATE_CHECK_IN = <<~GRAPHQL
  mutation CreateCheckInTrigger(
    $identifier: String!
    $description: String
    $kind: CheckInTriggerKindEnum!
    $syntax: String
    $timezone: String!
    $waitTimeMinutes: Int!
    $notifierIds: [String!]
    $appId: String!
  ) {
    createCheckInTrigger(
      identifier: $identifier
      description: $description
      kind: $kind
      syntax: $syntax
      timezone: $timezone
      waitTimeMinutes: $waitTimeMinutes
      notifierIds: $notifierIds
      appId: $appId
    ) {
      id
    }
  }
GRAPHQL
```

```ruby
# Updating an existing check-in
UPDATE_CHECK_IN = <<~GRAPHQL
  mutation UpdateCheckInTrigger(
    $id: String!
    $identifier: String!
    $description: String
    $syntax: String
    $timezone: String!
    $waitTimeMinutes: Int!
    $notifierIds: [String!]
    $appId: String!
  ) {
    updateCheckInTrigger(
      id: $id
      description: $description
      identifier: $identifier
      syntax: $syntax
      timezone: $timezone
      waitTimeMinutes: $waitTimeMinutes
      notifierIds: $notifierIds
      appId: $appId
    ) {
      id
    }
  }
GRAPHQL
```
```ruby
# Deleting a check-in
DELETE_CHECK_IN = <<~GRAPHQL
  mutation DeleteCheckInTrigger($id: String!, $appId: String!) {
    deleteCheckInTrigger(id: $id, appId: $appId) {
      id
    }
  }
GRAPHQL
```

We use the amazing [HTTP gem](https://github.com/httprb/http) for triggering API calls (just `HTTP.post(API_URL, json: { query:, variables: }).parse` is fine).

##### If someone wants to implement a similar sync to ours

We first generate the configuration in a YAML file based on the `clock.rb` file. There's no official API so we read `Clockwork.manager.instance_variable_get(:@events)` directly, generate cron syntax from the `at` and `period` and include the rake task name next to the config. All our jobs are defined as Ruby hashes so we can pass additional arguments if needed (like an override for max duration or custom cron syntax if it cannot be easily inferred due to `if` being a `proc`)

Afterwards we have a second script that compares this config with the check-ins on the AppSignal side and creates a list of operations (create/update/delete). It then triggers API calls in a row. We're prefixing all descriptions with a custom prefix (`[RAKE]`) to make sure we still have the flexibility to set up check-ins outside of the clockwork ones.

The third part is our custom rake instrumentation module which we `prepend` to `::Rake::Task` and which in `execute` method finds the check-in identifier from the YAML configuration based on the rake task name and wraps it in `Appsignal::CheckIn.cron(check_in) { super }`.

**Comment by unflxw** [comment]
Thank you! I'm sure this will be very helpful to others as a starting point.

I'm closing this issue, as it overlaps with a feature request that we're already tracking internally. If you're interested in this functionality, drop us a line at support@appsignal.com.
