### ISSUE TITLE
Permission issue when AppSignal logs to /tmp/appsignal.log

### ISSUE THREAD

**Issue by Manfred** [appsignal/appsignal-ruby#153]
On a few of our projects we deploy with a different user (deploy) than the application background user (app). Depending on who created the file last either deployment or booting the app fails unless we make sure to keep the log file around with the proper permissions.

```
Errno::EACCES: Permission denied @ rb_sysopen - /tmp/appsignal.log
```

I believe there are a number of things wrong here, in descending importance.
1. AppSignal should never crash my application
2. When used in Rails, AppSignal should not log outside of the Rails root unless explicitly instructed to do so
3. When creating temporary log files AppSignal should probably rely on Tempfile, which does the correct (and more secure) thing for each operating system

```
irb(main):001:0> require 'tempfile'
=> true
irb(main):002:0> Tempfile.open('appsignal') { |f| p f }
#<Tempfile:/tmp/appsignal20160914-5220-1clpiid>
=> #<Tempfile:/tmp/appsignal20160914-5220-1clpiid>
```

**Comment by thijsc** [comment]
This is indeed a pretty serious bug. Assumption number 1 is one of the most important things we try to live up to. I think assumption 2 and 3 make a lot of sense. We'll see if we can make that happen.

We'll work on a fix for this and will get back to you.

**Comment by tombruijn** [comment]
I've added better checks in #158  and #160 for point 1.
We will log to STDOUT if no viable log path is found.

Nothing for point 2 yet, we still fallback on `/tmp/appsignal.log` if the project path is not writable.

We can't really fallback on Tempfiles in Ruby as we log to the same logfile in our rust agent as well. We'll have to log to somewhere, anywhere, else if there's no viable log path on the system since the agent's STDOUT doesn't output in the Ruby process.

**Comment by tombruijn** [comment]
Hi again @Manfred, 

We've looked into the issue as previously updated. To come back to your original issues:

1. AppSignal should never crash my application
    - Indeed. We're doing our best to make sure it doesn't crash. Sometimes it does but we aim to fix that ASAP when it happens.
2. When used in Rails, AppSignal should not log outside of the Rails root unless explicitly instructed to do so
    - The team has discussed this and we don't necessarily agree. We'll fall back on the system `/tmp` dir when the Rails project directory is not writable. But if that's not writable either we will log to STDOUT if possible. The Rust agent however, can't do that and will most likely fail to start. This is a permission issue we're aware of.
3. When creating temporary log files AppSignal should probably rely on Tempfile, which does the correct (and more secure) thing for each operating system
    - We can't use the Ruby Tempfile class as we can't expect the Rust agent to reliably write to it. It's removed from the file system once the parent Ruby process exits. This makes it unreliable for us to write to between deploys and restarts of an application.

We're going to close this issue. Let me know if you have any other feedback regarding this issue. You can track our progress on supporting more methods of logging in #184
