### ISSUE TITLE
Sinatra applications wrapped in many middleware loses Sinatra config

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#157]
See PR #156 and comment https://github.com/appsignal/appsignal-ruby/pull/156#issuecomment-247567473

**Comment by wesoudshoorn** [comment]
@tombruijn can you give your opinion on wether we should fix this issue or ignore because it's a rare occurrence?

**Comment by tombruijn** [comment]
Well it's really @jeffkreeftmeijer's issue ;)

But yes I think it's an important issue and could be quite common. Sinatra apps with multiple middlewares where AppSignal is not loaded first lose part of their config. So we're changing the behavior of Sinatra apps without the user knowing. That's something we should never do. Previously this raised an error, now we're hiding it, but it should still be fixed.

**Comment by thijsc** [comment]
Is this related to #149?

**Comment by tombruijn** [comment]
No it's a different issue unfortunately

**Comment by tombruijn** [comment]
We might be able to review/fix this in #329
