### ISSUE TITLE
Instrument Rack middleware

### ISSUE THREAD

**Issue by thijsc** [appsignal/appsignal-ruby#159]
If there are Rack middlewares running before your requests we should instrument these so you can see how they influence performance.

## Requests

- https://github.com/appsignal/appsignal-server/issues/2514

**Comment by tombruijn** [comment]
If at all possible, find a way to track errors inside ActionDispatch::ShowExceptions and ActionDispatch::DebugExceptions, even if they're kind of private errors. Namely `ActionController::RoutingError` for routing errors and non existing routes

As suggested here:
https://app.intercom.io/a/apps/yzor8gyw/inbox/conversation/6039076300?nsrc=slack

**Comment by tombruijn** [comment]
Review how we would want to do this in combination with #329 
Timeboxed research about methods we can do this with one or more middlewares and potential rack monkey patches.

**Comment by tombruijn** [comment]
https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540709/conversations/11368616241

**Comment by tombruijn** [comment]
- start only one transaction per request. If another transaction is active, don't start a new one.
- HAve the middleware complete their own transaction? Rather than `Appsignal::Transaction.complete_current!`

**Comment by tombruijn** [comment]
Related issue: https://github.com/appsignal/appsignal-ruby/issues/329

**Comment by jeffkreeftmeijer** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/16660366147

**Comment by tombruijn** [comment]
Closing in favor of #329
