### ISSUE TITLE
Sinatra integration doesn't listen for APPSIGNAL_APP_ENV

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#161]
The Sinatra integration doesn't listen for APPSIGNAL_APP_ENV, but instead always listen for the application's environment

https://github.com/appsignal/appsignal-ruby/blob/45f232ecdf1cc22ec1630227d7c51e38ee69722d/lib/appsignal/integrations/sinatra.rb#L9

Padrino does listen for it:

https://github.com/appsignal/appsignal-ruby/blob/45f232ecdf1cc22ec1630227d7c51e38ee69722d/lib/appsignal/integrations/padrino.rb#L11

Let's update it and add a spec as well

---

Reported in: https://app.intercom.io/a/apps/yzor8gyw/inbox/conversation/6059337748

**Comment by Fruetel** [comment]
Any estimation when this will be available in the official gem?

**Comment by tombruijn** [comment]
Hi @Fruetel, we plan to release the 1.4.0.beta1 gem today. Hope to ship a release version sometime this week.

**Comment by Fruetel** [comment]
Nice, thanks for the fast feedback loop!

**Comment by Fruetel** [comment]
We have it in production now, works like a charm. Thanks!
