### ISSUE TITLE
appsignal_instrument_method does not work with methods that yield

### ISSUE THREAD

**Issue by DMA57361** [appsignal/appsignal-ruby#162]
Using appsignal gem v1.3.4 on a Rails 4.2.6 application. As per the subject I think the `appsignal_instrument_method` method (and it's class equivalent) cause a problem if used on a method that attempts to `yield` to a block.

Here's a quick example class with three super simple methods that just yield:
```
class Example
  def block_func
    yield
  end

  def i_block_func
    yield
  end
  appsignal_instrument_method :i_block_func

  def self.ci_block_func
    yield
  end
  appsignal_instrument_class_method :ci_block_func
end
```

If I call those three methods the result is:
```
[2] pry(main)> Example.new.block_func{ puts 'block_func works!' }
block_func works!
=> nil
[3] pry(main)> Example.new.i_block_func{ puts 'i_block_func works!' }
LocalJumpError: no block given (yield)
from (pry):7:in `i_block_func'
[4] pry(main)> Example.ci_block_func{ puts 'cd_block_func works!' }
LocalJumpError: no block given (yield)
from (pry):12:in `ci_block_func'
```

Note that the methods that have been marked with `appsignal_instrument_method` and `appsignal_instrument_class_method` both fail in the same way, seems like the block isn't making it to the method wrapped by your instrumentation.

**Comment by tombruijn** [comment]
@DMA57361 yep, that's correct. I'll see if I can fix that really quickly

**Comment by tombruijn** [comment]
@DMA57361 added a PR with support at #163
