### ISSUE TITLE
Remove rescue Exception occurences

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#168]
As discussed before this is not recommended for various reasons. We shouldn't capture Exception in AppSignal logic (errors that could occur by calling a method on `nil` around listening for user errors), but we should capture more exceptions than just `StandardError` that could come from code by users. For more on that, see #174

Most importantly is that we don't rescue system quit or kill calls, and if we do, we re-raise them.

Secondly, apparently quite a couple specs we have are actually broken 😱 , but because we capture all Exceptions we don't see them.

Expect some PRs soon

**Comment by thijsc** [comment]
I think this one can be closed after the various merged PRs?

**Comment by tombruijn** [comment]
There are four occurrences remaining, they are also listed as Rubocop violations in `.rubocop_todo.yml`.

One in the minutely probe and 3 in the rack streaming listener.

I could look at it sometime this week(end), we can keep the issue open until then?

**Comment by tombruijn** [comment]
This will all be finally resolved in #356
