### ISSUE TITLE
Possible NoMethodError?

### ISSUE THREAD

**Issue by Xanthus** [appsignal/appsignal-ruby#195]
First off, apologies for the very random issue creation and also in case this isn't a real issue because I haven't tested it (I don't use Appsignal, I was just snooping while figuring out how it works), but this might be of interest.

Pretty sure this is going to generate a NoMethodError (unless there's a global #backtrace method patched onto Kernel somewhere by the gem)

https://github.com/appsignal/appsignal-ruby/blob/master/lib/appsignal/js_exception_transaction.rb#L48

````ruby

def set_sample_data
      {
        :params       => @data['params'],
        :session_data => @data['session_data'],
        :environment  => @data['environment'],
        :tags         => @data['tags']
      }.each do |key, data|
        next unless data.is_a?(Array) || data.is_a?(Hash)
        begin
          @ext.set_sample_data(
            key.to_s,
            Appsignal::Utils.json_generate(data)
          )
        rescue *Appsignal::Transaction::JSON_EXCEPTIONS => e
          Appsignal.logger.error("Error generating JSON (#{e.class}: #{e.message}) for '#{backtrace.inspect}'") # Perhaps someone meant '#{e.backtrace.inspect}'?
        end
      end
    end

````

**Comment by tombruijn** [comment]
Hi @Xanthus, thanks for examining our code! We must not have had a test case for this 🤔

However, we removed this rescue block in #175 reworking the way we generate this sample data. So it's no longer an issue in the (unreleased) gem version 1.4.

Thanks for the report! Even if you don't use AppSignal (sure you don't want to start a free trial? 😉 ) Let us know if you found anything else that strikes you as odd. We'd love the feedback! We're continuously improving our integrations to make them more stable :)

**Comment by tombruijn** [comment]
Also, to show our thanks, if you send your address to support@appsignal.com (with a reference to this issue) we'll send you a box of delicious stroopwaffels !

**Comment by Xanthus** [comment]
Hi @tombruijn 

Sure, no problem! Happy to help. Stroopwaffels sound great - do you deliver to London or do I have to wait till I visit Amsterdam again? :)

The service looks quite interesting. I found it because I'm subscribed to the Ruby Magic newsletter (good job on that). I'm starting pre-launch trialing for a new app in a few months, I'll probably give it a go then, thanks!

**Comment by tombruijn** [comment]
We deliver! We ship worldwide even. London's not that far either :) also, feel free to visit when you're in Amsterdam. 

Great to hear you're considering us. Let me know if you have any questions!
