### ISSUE TITLE
Monitor transactions in Rake hook

### ISSUE THREAD

**Issue by christofdamian** [appsignal/appsignal-ruby#206]
This could be easily done in the rake hook, unless I am missing something. 
I our application I am am now also patching ```Rake::Task```
```ruby
# Add transaction monitoring to all rake tasks. Code stolen from the appsignal
# Rake hook, which only does the exception handling.
::Rake::Task.class_eval do
  alias :execute_without_appsignal_transaction :execute

  def execute(*args)
    Appsignal.monitor_transaction(
      "perform_job.rake.#{name}",
      method: name,
      metadata: { args: args }
    ) do
      execute_without_appsignal_transaction(*args)
    end
  end
end
```
I can create a pull request if nobody tells me I am really missing something.

**Comment by tombruijn** [comment]
Hi @christofdamian,

Thanks for the suggestion!

It's a conscious decision not to monitor all Rake tasks' performance. We'd track all kinds of Rake tasks, even those that are always going to be slow. We wouldn't want to monitor Rails asset compilation for example. You can still add this logic to your own setup and use it, but it's probably not something we would want to turn on by default.

Let me know if you have any other questions

**Comment by christofdamian** [comment]
OK, thanks for the quick response. For us it is useful as we want to see who is using resources like CPU, and SQL. 
But maybe not useful for everyone as you say.

**Comment by tombruijn** [comment]
Ah yes, well luckily the integration for that is easy 😄 

I'll close the issue. Feel free to create new issues if you have any suggestions!

**Comment by kjeldahl** [comment]
Just a note for other running into this: 

I added the above code as I have several rake task I would like monitor and then the Resque integration stopped working as the resque worker is started by a rake task. 

So I added a simple filter by name to the above code to skip the  monitor_transaction for resque rake tasks.
