### ISSUE TITLE
Try booting the agent with given config in `appsignal diagnose`

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-ruby#211]
Sometimes permission problems prevent the agent from booting, the only way to figure out what's wrong is to boot the agent manually with all ENV vars from the config set.

Ideally the `appsignal diagnose` command would try to boot the agent with the given config and log the output, so we can diagnose permission problems easily.

**Comment by tombruijn** [comment]
We'd probably have to try to start the agent without daemoning it, right? Otherwise, if a logger issue occurs, we'd lose any logs from an agent that failed to start.

**Comment by tombruijn** [comment]
Added in #221 and will be released in 2.0.4
