### ISSUE TITLE
Misleading message output when running on Heroku

### ISSUE THREAD

**Issue by walro** [appsignal/appsignal-ruby#241]
Hello,

We are seeing the following message being emitted upon start up of our application on Heroku:

`2017-01-27T08:19:57.855597+00:00 app[web.2]: appsignal: Unable to log to '/app/log'. Logging to '/tmp' instead. Please check the permissions for the application's (log) directory.`

On Heroku you are supposed to write to `STDOUT`, which the the gem [already ensures](https://github.com/appsignal/appsignal-ruby/blob/5e7f5c42a7995811cfba13e054f69d55d501d0f6/lib/appsignal/config.rb#L152).

However, the [log_file_path method](https://github.com/appsignal/appsignal-ruby/blob/5e7f5c42a7995811cfba13e054f69d55d501d0f6/lib/appsignal/config.rb#L92-L108) does not seem to take this into account, leading to the message above.

I am not sure how to best solve it as I don't really know what return value of `log_file_path` would make the most sense. I guess you are setting this value in `ENV` for easier debugging purposes (it does not seem to be used internally by the gem at least) if I understood things correctly so maybe setting it to `STDOUT` could work out.

**Comment by tombruijn** [comment]
Hi @walro,

We're aware of this warning on Heroku and similar hosting platforms. Our Ruby gem logs to STDOUT as much as it can, but our agent running in a separate process writes to a log file and by default that's the `log/` directory in the application's root directory.
Since that path is not writable the warning is logged. You can safely ignore it, or set the `log_path` to `/tmp` to hide it.

**Comment by walro** [comment]
Ah right, didn't think of the agent. Thanks for getting back to me, I think we'll simply ignore the message for the time being.

**Comment by tombruijn** [comment]
Cool :)

I've also made a note to add some more details about that warning in our documentation, gem and website, and why we use log files at all when `log: stdout` is configured.
