### ISSUE TITLE
Stub frontend error catcher in development

### ISSUE THREAD

**Issue by timraasveld** [appsignal/appsignal-ruby#247]
Right now, I think Rails development workflow is worsened when the frontend error catcher is enabled.

When you make a programming error resulting in a 500 , you see two exceptions in the Rails and browser log:
1. First, your Rails error (the one you are interested in)
2. Then, a 404 not found for `/appsignal_error_catcher`

This causes noise and unneccesary scrolling :(

Would it make more sense to have a development implementation of the frontend error catcher that returns `204 no content` without doing anything?

**Comment by tombruijn** [comment]
Hi @timraasveld, sorry the for the belated response.
The frontend error catcher is enabled but the endpoint is not found? Is that only the case in development? Or have you manually disabled the frontend error catcher only for development?

**Comment by timraasveld** [comment]
Yes, the endpoint is enabled, and it's only the case in development. (404)
We didn't override the error catcher in development, but obviously did set `enabled: false` for the gem in development.

Feel free to take a look at [the config](https://github.com/roqua/screensmart/blob/b5cf71f6cfc3e5c8fe5bc3c22e6df20e8d65fe9f/config/appsignal.yml) in one of the projects.

Right now I worked around it by using this "hack" in `window.onerror`:
```
  appsignal.sendError(error) if error && window.environment != 'development'
```

**Comment by tombruijn** [comment]
Hi @timraasveld this was fixed in #263. Let me know if this still happens :)

**Comment by timraasveld** [comment]
@tombruijn that does the trick, thanks a lot! 👍

**Comment by tombruijn** [comment]
yay 🎉 
Thanks for letting me know!
