### ISSUE TITLE
APPSIGNAL_INSTRUMENT_SEQUEL has no effect

### ISSUE THREAD

**Issue by Fruetel** [appsignal/appsignal-ruby#251]
In my environment, I configure

`export APPSIGNAL_INSTRUMENT_SEQUEL="false"`

but I still see appsignal metrics for SQL calls. Also, the code in appsignal-ruby/lib/appsignal/config.rb does not suggest that the environment variable is actually evaluated.

**Comment by thijsc** [comment]
That should actually work. It gets translated to the config option `: instrument_sequel ` and then gets used here: https://github.com/appsignal/appsignal-ruby/blob/master/lib/appsignal/hooks/sequel.rb#L37

Which version of the gem are you using? Could you run `bundle exec appsignal diagnose` and make sure the config option is actually there?

**Comment by Fruetel** [comment]
Appsignal 2.0.6 - I need to avoid 2.1.0 due to DNS issues.

`
Projekte/queue-elements [ export APPSIGNAL_INSTRUMENT_SEQUEL="false"                                                                         
Projekte/queue-elements [ appsignal diagnose | grep -i sequel                                                                                
  instrument_sequel: true
`

**Comment by thijsc** [comment]
This was indeed a bug, fix will be released in the next release.
