### ISSUE TITLE
Test transaction from extension with `appsignal_transaction_to_json`

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#252]
- [x] Implement `appsignal_transaction_to_json` in the Gem's C-extension #291 
- [x] Add it to tests to check if all the assertions are correct.
- [ ] Add test mode to extension so that we don't have to stub the `complete` call

See: https://github.com/appsignal/appsignal-agent/pull/228

**Comment by thijsc** [comment]
`appsignal_transaction_to_json` can return an empty string, you should interpret that as `nil`. I'd return `Qnil` from the C glue code in that case.
