### ISSUE TITLE
Padrino's payload action uses the older request_obj method even when the newer action-based method is available.

### ISSUE THREAD

**Issue by liamnoone** [appsignal/appsignal-ruby#253]
In the Padrino integration there's two-three possible options when reporting the name of the request.

The first is the older "route_obj" method. Based on the documentaiton alongside the code this is considered the fallback version, with better support.

This produces data like `App:/demo/hello(.:format)?`, which isn't the prettiest output in the dashboard.

The other method is the "action"-based method. This adds the controller name and the name of the route and looks preferable. 

It produces data like `App:demo#hello` which is a bit prettier and more rubyesque. The slight alternative is the "fullpath" version, which produces data like `App:demo#/demo/hello`. 

However the code proritises the route_obj version, while it looks like the preferred option is the action-based version. Since route_obj is still present in the latest Padrino codebase so it's picked up first.

The codechange isn't difficult, and has been included next, which could simply be a pull request. However this new data will mess up everybody's data, adding metrics into new "slots" in the data, and losing long-term data like performance history. So I'd rather highlight this and defer the decision to the Appsignal team.

The changed version of the integration: 

```ruby
# lib/appsignal/integrations/padrino.rb

  def get_payload_action(request)
    # Short-circut is there's no request object to obtain information from
    return settings.name.to_s if request.nil?

    # Newer versions expose the action / controller on the request class
    # Newer versions still expose a route_obj so we must prioritize the action/fullpath versions
    if request.respond_to?(:action)
      return "#{settings.name}:#{request.controller}##{request.action}"
    elsif request.respond_to?(:fullpath)
      return "#{settings.name}:#{request.controller}##{request.fullpath}"
    end

    # Older versions of Padrino work with a route object
    if request.respond_to?(:route_obj) && request.route_obj
      return "#{settings.name}:#{request.route_obj.original_path}"
    end

    # Fall back to the application name if we haven't fit into any previous options
    settings.name.to_s
  end
```

**Comment by thijsc** [comment]
Thanks for researching this. The proposed change looks good. It would indeed change the behaviour, so it should at least be in a minor release. I think we'll release 2.2 quite soon, this could be a part of this.

Do you already have a branch of this on the gem?

**Comment by liamnoone** [comment]
I don't currently have a branch of the gem with this change.

Other than adding tests this is the required change to close this issue from what I can tell.
I avoided adding a branch + MR due to it changing the output as mentioned.

**Comment by tombruijn** [comment]
I've created a PR for this in #265. Could you try it out @liamnoone ? And see if you're getting the results you expect

**Comment by liamnoone** [comment]
Hi,

Thanks!

I ran some initial testing and the data entries are much nicer now!

The testing was only some brief testing of different endpoint configurations, so it wasn't an exhaustive test. I'll run it more during the week if you'd like some longer testing but to me it looks good now and no exceptions appeared throughout three different apps.

**Comment by tombruijn** [comment]
Great! Thanks for the feedback. We'll release this in gem version 2.2 sometime soon.
