### ISSUE TITLE
Backburner background processor library support

### ISSUE THREAD

**Issue by tdegrunt** [appsignal/appsignal-ruby#277]
Would it be possible to support Backburner out of the box?

It's the first option mentioned under [ActiveJob::QueueAdapters](http://api.rubyonrails.org/classes/ActiveJob/QueueAdapters.html), I realise it's not the most popular option (though it should be!), but I hope you can still support it out of the box.

I've checked the documentation here: http://docs.appsignal.com/ruby/instrumentation/background-jobs.html, but I would much prefer support straight in the Appsignal gem.

**Comment by tombruijn** [comment]
Hi @tdegrunt ,

Sorry for the very late response. This message slipped through somehow.

We don't have any plans to support backburner right now. This is the first request we've received for it.

Would you be using it with ActiveJob?
We have an open issue for improving our ActiveJob support #330. Perhaps we can support it through independent ActiveJob support? (Most of our ActiveJob support is now per integration (Sidekiq, Resque, etc).)

**Comment by tombruijn** [comment]
Hi again @tdegrunt,

We're shipping an improved version of ActiveJob support that will work for all listed adapters, including Backburner.
You can try it out now in version 2.11.0.beta.2. Let me know if you do and if it works for you :) (Either here or at support@appsignal.com)

Closing this issue for now as we will support it through activejob.
