### ISSUE TITLE
Review ActiveJob support

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#330]
Support ActiveJob without the need for additional integration such as Sidekiq, Resque, etc. Currently it's set up that we only support a couple libraries with ActiveJob support.

This doesn't mean we remove the separate integrations for these integrations, for use without ActiveJob, but that we generally support ActiveJob and some libraries separately.

Would resolve #277 
See private issue: https://github.com/appsignal/appsignal-server/issues/4719

**Comment by jeffkreeftmeijer** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/20063993426

**Comment by tombruijn** [comment]
Improved ActiveJob support now available in 2.11.0.beta.2. It's available for testing. If anyone following this issue tests this, let me know :)
