### ISSUE TITLE
Allow appsignal_app_env to be set in appsignal.yml

### ISSUE THREAD

**Issue by bpeicher** [appsignal/appsignal-ruby#337]
It appears that this is the only configuration option that can't be set in appsignal.yml: https://docs.appsignal.com/ruby/configuration/options.html#appsignal_app_env

Use case: we have a generic `RELEASE_STAGE` variable that defines our various environments. It contains the exact value that should be submitted to appsignal as the app environment, but we aren't allowed to do this for some reason:

```
default: &defaults
  app_env: <%= ENV['RELEASE_STAGE'] %>
```
Instead we are forced to define another environment variable with the same value or do the following:
```
ENV['APPSIGNAL_APP_ENV'] ||= ENV['RELEASE_STAGE']
```
It would be easier and cleaner if this could simply be defined in the yaml.

**Comment by thijsc** [comment]
The thinking behind this is that the yml configures for an environment. I do see an option that we add a top-level attributes for this:

```
app_env: <%= ENV['RELEASE_STAGE'] %>

default: &defaults
```

Another could be adding something to make the name of the env var configurable. That might be the most flexible one actually. What do you think?

**Comment by bpeicher** [comment]
Either one is fine with me - and much cleaner than our workaround. Thanks for looking at it.

**Comment by tombruijn** [comment]
Quick comment, this would be fixed if using ERB to also create the env group:

```yml
<%= ENV['RELEASE_STAGE'] %>:
  active: true
```

We should add this to the docs: https://github.com/appsignal/appsignal-docs/issues/176

**Comment by tombruijn** [comment]
We're going to improve the docs for this. A combination of env and config file will require the solution in my previous comment for dynamic env names that can't be added as static names to the config file.
