### ISSUE TITLE
Standard startup logging is verbose

### ISSUE THREAD

**Issue by jqr** [appsignal/appsignal-ruby#349]
The default logging is a bit excessive for starting a Rails console, producing 4 lines in a simple Rails application.

```
[2017-09-23T17:19:32 (process) #4][INFO] appsignal: Loading Rails (5.1.4) integration
[2017-09-23T17:19:33 (process) #4][INFO] appsignal: Starting AppSignal 2.3.3 (/app/bin/rails, Ruby 2.4.2, x86_64-linux)
[2017-09-23T17:19:33 (process) #4][INFO] appsignal: Installing action_cable hook
[2017-09-23T17:19:33 (process) #4][INFO] appsignal: Installing active_support_notifications hook
[2017-09-23T17:19:33 (process) #4][INFO] appsignal: Installing net_http hook
>
```

Some options I see to improve:

1. Combine these into one:  `Starting AppSignal 2.3.3 (/app/bin/rails, Ruby 2.4.2, x86_64-linux) with action_cable, active_support_notifications and net_http hooks`
2. Set some/most of them to DEBUG so we only see them when `debug: true`.
3. Allow specifying the `log_level` in the config, so maybe: `log_level: WARN`.

**Comment by tombruijn** [comment]
Hi @jqr ,

This should only happen with the config option `log: "stdout"` is this the case here?

About the logs themselves, yes, some can probably be moved to the debug level. On the other hand, it's often useful for us to know what's active by reading an app's log without having to ask a user to set the debug level to true first, which can take a few days to deploy and encounter the error again.

We're going to review it, and share any updates here.

**Comment by jqr** [comment]
Yeah this is on Heroku, which is `STDOUT` logging.

I can see that being handy for your debugging, though I think either submitting it through the data layer or doing solution 1 above make equal sense.

In my case I'm likely to monkey patch this library to remove the noise, but it seems that other users would appreciate this change as well.

**Comment by InteNs** [comment]
any updates on this?
we are running rake tasks with cron and the logs are full with appsignal appsignal appsignal.
we also use stdout because everything runs on docker and i would love to configure `APPSIGNAL_DEFAULT_LOG_LEVEL` in order to control these startup messages:

![image](https://user-images.githubusercontent.com/6474105/94405434-d5364280-0170-11eb-9b1e-b3f3fc6aff74.png)

**Comment by grk** [comment]
Just wanted to add a vote for this, would be great if we could reduce this noise.
