### ISSUE TITLE
Improve search ability of documentation

### ISSUE THREAD

**Issue by niila** [appsignal/appsignal-ruby#371]
Feedback from a user:

> For your question what can be improved: Some part are really well explain when you discover the tool, but sometime it's hard to get the info when you're getting used to the tool but look for a specific information. 

> For example I was looking for the meaning of the arguments of the Appsignal.monitor_transaction method, I knew I read it somewhere but I had to search for a while before finding it.
A search box with an API like the Rails API documentation would be great !

Tom via Slack: 
we should probably also link to the rubydocs website from docs.appsignal.com for certain methods: http://www.rubydoc.info/gems/appsignal/2.4.1/Appsignal.monitor_transaction

**Comment by tombruijn** [comment]
Updated the documentation for the `Appsignal.monitor_transaction` helper method in commit https://github.com/appsignal/appsignal-ruby/commit/21a89e465ca9f22c1c5330f3046b225752c85228

The part of our docs page needing search is something that should be an issue on the docs repo. I've created one here: https://github.com/appsignal/appsignal-docs/issues/137

Closing
