### ISSUE TITLE
Fetch queue time regardless of namespace

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-ruby#378]
Right now we only collect queue metrics if the namespace is `web` or `background` ( https://github.com/appsignal/appsignal-ruby/blob/b577992e0211c82898be43148a22b5e9a2d48efe/lib/appsignal/transaction.rb#L231 )

However it would be nice if we could get the queue times for custom namespaces. You'd probably have to specify the kind of queue time metric to fetch (headers vs bg job start time). 

https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/conversation/13774891912

**Comment by tombruijn** [comment]
Picked up in #602 and merged. Will be released in Ruby gem 2.11. (We're now at 2.10.5.)
