### ISSUE TITLE
Missed `Mysql2::Error`

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-ruby#382]
As reported via [support](https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540654/conversations/14509052300) (private Intercom link).

In a controller, we missed a `Mysql2::Error` ("Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction"), which inherits from `StandardError`.

**Comment by tombruijn** [comment]
We can't reproduce this right now. We hope that #159 will fix this in the future.
Closing this issue for now to clean up the repo. Do let us know if you have this issue.
