### ISSUE TITLE
🚀 Configuration option for `APP_REVISION`

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-ruby#386]
We'd like to expose the `:revision` configuration option, like we're adding in the Elixir integration (https://github.com/appsignal/appsignal-elixir/issues/215).

**Comment by tombruijn** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540709/conversations/14396986780

**Comment by tombruijn** [comment]
Added in #388
