### ISSUE TITLE
🚀 Configurable :request_headers / APPSIGNAL_REQUEST_HEADERS

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-ruby#389]
Depends on decisions made in https://github.com/appsignal/appsignal-elixir/issues/317. As requested via [support](https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/14994864230) (private Intercom link).

**Comment by tombruijn** [comment]
Added in #395 and #406
