### ISSUE TITLE
Allow more transaction variables to be set with `send_error`

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-ruby#407]
Right now `Appsignal.send_error` is quite limited, you can only set the error, tags and the namespace. This is not always enough to debug an error that happens in production.

Maybe we can find a way to allow more transaction variables to be set, preferably in a backwards compatible way. 

One possible way could be to accept a block that yields the transaction e.g.

```ruby
Appsignal.send_error(ex, {}, "admin") do |transaction|
  transaction.params = params
  transaction.set_action_if_nil "AdminLoginWorker"
end
```

This would give a lot of flexibility to the `send_error` method, but it would also force users to get familiar with our `transaction` object and it's methods. Is this something we want?

Do you have suggestions for this @tombruijn @jeffkreeftmeijer @thijsc ?

Tagging @StephanMeijer  as requested

**Comment by tombruijn** [comment]
Maybe we can fix the hybrid of adding errors as well when we touch this: https://github.com/appsignal/appsignal-ruby/issues/176
as long as we keep the explicit `send_error` helper method.

**Comment by StephanMeijer** [comment]
Thanks for opening this issue.
100 characters of data is too less if you want to send some parameters to AppSignal.

**Comment by tombruijn** [comment]
Also notify: https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/16076459192

**Comment by tombruijn** [comment]
Removing integration level limits in https://github.com/appsignal/appsignal-ruby/pull/418 and falling back on the extension and processor limits instead, which increases it to 256 characters (at time of writing).

This issue will continue to be used for the DSL of the `send_error` helper method to allow for other transaction metadata to be set. Moving back to WIP.

For the "discuss" label, I think we should implement it as described in this issue. Perhaps even deprecate the tags and namespace arguments from the `send_error` method.

**Comment by tombruijn** [comment]
Added in #481
