### ISSUE TITLE
Installer wrongly detects app as Rails

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#432]
> It will help to understand what goes wrong if the script detects Rails by a mistake and raises an exception like this one: https://gist.github.com/kostyadubinin/e2f5344b245d4278263ba87cd374370b
> 
> The script detects Rails by a mistake in this case:
> 
> - the application is written with Sinatra
> - you don't use Bundler (not sure if this is required)
> - the Rails gem is installed and require "rails" doesn't raise an error
> 
> When the script detects Rails by a mistake it tries to require config/application.rb (which doesn't exist) and raises an exception.

From https://github.com/appsignal/appsignal-ruby/pull/431

We should rescue the LoadError if the application.rb file cannot be found and fall back on the next framework or default installation. Or maybe ask the user what they want?

**Comment by kostyadubinin** [comment]
Specifying the framework explicitly could be convenient.
