### ISSUE TITLE
Can't see Delayed Job statistic and exception reports

### ISSUE THREAD

**Issue by NOX73** [appsignal/appsignal-ruby#485]
I can't see any information about my background jobs in the background section.Appsignal works fine for application requests.

I expect to see statistic and exception reports on appsignal dashboards from Delayed Jobs.

ruby 2.5.0p0
rails (5.2.2)
delayed_job (4.1.5)
appsignal (2.8.2)

```
irb(main):020:0> Appsignal::Hooks.hooks[:delayed_job]
=> #<Appsignal::Hooks::DelayedJobHook:0x000000edd99d9690 @installed=true>
irb(main):022:0> ::Delayed::Worker.plugins
=> [Delayed::Plugins::ClearLocks, Appsignal::Hooks::DelayedJobPlugin]
```

How can I investigate an issue?

**Comment by thijsc** [comment]
Hi, thanks for reporting!

For these kinds of issues you're best off us asking in the chat in the or on support@appsignal.com, there's probably something configured not right.

**Comment by NOX73** [comment]
@thijsc are you sure it's a configuration issue?

**Comment by thijsc** [comment]
It's hard to know for sure. We always do debugging of these kinds of issues over the support channel because you discuss details about the specific application. If there turns out to be a bug we'll open an issue.

**Comment by NOX73** [comment]
Ok, will chat by email

**Comment by tombruijn** [comment]
Continued in our support channel. Will report back with results
