### ISSUE TITLE
Add support for GraphQL Instrumentation

### ISSUE THREAD

**Issue by perezpaya** [appsignal/appsignal-ruby#486]
As heavy users of Appsignal for instrumentation on web and background jobs we would like to receive support to identifying each query so we can measure performance issues and track errors accurately.

All our API traffic is aggregated through Graphql#execute and we fail identifying performance issues there.

Do you currently give support in some way or have a way of setting up our application configuration in order to have better tracing of our usage?

Thank you!

**Comment by jvanbaarsen** [comment]
We do! You can set this up by altering your GraphQL controller a bit.

I created a small snippet for you that can help you with this:

```ruby
class GraphqlController < ApiController
  #[...]
  def create
    # [ Your GraphQL logic ]
  rescue => e
    Appsignal.set_error(e)
    render :json => { :errors => [:message => SERVER_ERROR_MESSAGE] }, :status => :server_error
  ensure
    Appsignal::Transaction.current.set_namespace("graphql")
    Appsignal::Transaction.current.set_action(params['operationName'] || 'Unknown')
  end

  #[...]
end
```

In the `ensure` block we set a custom namespace, this might help you with filtering only GraphQL related information in your dashboard.

`Appsignal::Transaction.current.set_action(params['operationName'] || 'Unknown')` This sets the action for this controller to the name of the query you're executing.

Hope this helps you along, if not let me know 👍

**Comment by tombruijn** [comment]
Closing. Let us know if this didn't fix it for you!

**Comment by sergiotapia-papa** [comment]
@tombruijn How can we do this for Elixir and Phoenix? Looking for the same solution in Phoenix.

**Comment by tombruijn** [comment]
@sergiotapia-papa you mean in combination with absinthe? We have a tracking issue for it here: https://github.com/appsignal/appsignal-elixir/issues/176
With some small tweaks as described in https://docs.appsignal.com/elixir/integrations/absinthe.html (which we give no guarantee of working) you should get basic single process and non-async absinthe support. We're working to improve this in the future.
