### ISSUE TITLE
Bump transaction reuse log message to warning

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#489]
When a transaction is already running and another one is created already it's usually an indication of a problem. Currently we log it as a debug log, but this requires turning on debug logging before we see it in the log

I suggest we bump the debug log up to a warning so it's easier to spot.

https://github.com/appsignal/appsignal-ruby/blob/02d99a3035856fda341c2543f9ee559769e0b9a6/lib/appsignal/transaction.rb#L28-L30

See if we can add a separate warning, instead of warn for every occurrence. This would prevent us from spamming the logs.

**Comment by jvanbaarsen** [comment]
Fixed by #525
