### ISSUE TITLE
Puma minutely probe reports 0 for all metrics

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#502]
With this config all the probe's metrics are reported as 0.
Let's test why this is going wrong and fix it.

```ruby
# config/puma.rb
workers 2

threads 5, 5

port 3000

app_dir = File.expand_path("../..", __FILE__)
shared_dir = "#{app_dir}/shared"

# Default to production
rails_env = "development"
environment 'development'

# Set up socket location
bind "unix:///#{shared_dir}/sockets/puma.sock"

stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true

pidfile "#{shared_dir}/pids/puma.pid"
state_path "#{shared_dir}/pids/puma.state"
# activate_control_app

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
end
```

```sh
bundle exec puma -C config/puma.rb
```

Reported in https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540709/conversations/21393974417

**Comment by tombruijn** [comment]
This happens when `preload_app!` is missing from the `config/puma.rb` file. It starts working when you add that. Without it the stats object will always be empty/0.

**Comment by tombruijn** [comment]
There are some cases, like phased restart, where `preload_app!` is not an option.

It currently reports 0 values because the minutely probe runs in every worker (that creates duplicate metrics, but more importantly it returns 0 for all metrics).

If we can run the minutely probe in the "main" process it reports proper values. We need to find a way to _only_ run the minutely probe process in the "main" process and not in the workers.

**Comment by tombruijn** [comment]
Follow up from https://github.com/appsignal/support/issues/54#issuecomment-538993805 (private link)

**Comment by tombruijn** [comment]
Trying out if this config override works:

```ruby
# config/puma.rb

before_fork do
  require "appsignal"
  Appsignal.start
end

on_worker_boot do
  require "appsignal"
  Appsignal::Minutely.stop
end
```

The idea is that we manually start AppSignal in the main process. Which starts the minutely probes.

Then, on start of every worker, we stop the minutely probes, which is started by default. By disabling it it won't collect and send the 0 values Puma reports in workers.

No `preload_app!` needed here so it should work with phased restarts. Asked a user to test it, waiting for results.

**Comment by tombruijn** [comment]
I can't reliably load AppSignal in Puma's clustered mode without `preload_app!`. If I don't `preload_app!` AppSignal isn't loaded in the master process and requires it to be loaded manually, for which getting the right conditions I haven't found yet.

If I load AppSignal manually Rails isn't loaded by default and AppSignal doesn't load the Railtie because it can't detect Rails. If I load Rails and AppSignal beforehand it seems to defeat the purpose of not calling `preload_app!`, because I'm basically preloading the app manually that way. And I don't know how this will break in a phased restart.

I tried to create a Puma plugin to move all the config in there, setting all the hooks automatically. This should make it easier for the user to configure AppSignal for Puma, but apparently plugins reset already defined config on load: https://github.com/puma/puma/blob/2d46f0b63a0a9113603d67b8518acb7ca57af814/lib/puma/dsl.rb#L55
Which makes it hard to recommend to our users because we then magically unset all their config on load without warning. So a Puma plugin doesn't seem like an option.

Even without all that there still needs to be a path that allows us to only start the Minutely probe thread in Puma's main process. This would require the following:

1. A way to not start the minutely probe thread automatically in Puma workers, or;
2. Stopping the Minutely thread on boot in Puma workers. With the `on_worker_boot` hook. When set in `config/puma.rb` this also requires us to `require "appsignal"`.

To get the minutely probe to work as described in option 2, I had to do this:

```ruby
# config/puma.rb

before_fork do
  require "appsignal"
  Appsignal.start
end

on_worker_boot do
  require "appsignal"
  Appsignal::Minutely.stop
end
```

The problem now is that the Rails integration is broken. Which requires a `require "rails"` in `before_fork` to function again. I wouldn't consider that a good solution.

**Comment by xadamy** [comment]
Waiting for customer feedback.

**Comment by tombruijn** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/21377336095
