### ISSUE TITLE
Autodetect Cloudfoundry based containers

### ISSUE THREAD

**Issue by jvanbaarsen** [appsignal/appsignal-ruby#521]
When a customer is running in Cloudfoundry we don't autodetect that they are running inside a container, this means they would have to manually set the `running_in_container` option to true.

It would be great if we can autodetect this, and set it for the customer.

[Internal link](https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/21679499792)

**Comment by jvanbaarsen** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/21679499792

**Comment by tombruijn** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/21679499792

**Comment by jvanbaarsen** [comment]
Issue moved to [appsignal/appsignal-agent #437](https://github.com/appsignal/appsignal-agent/issues/437) via [**ZenHub**](https://www.zenhub.com/)
