### ISSUE TITLE
Sidekiq Enterprise middleware position

### ISSUE THREAD

**Issue by 97jaz** [appsignal/appsignal-ruby#526]
We're using sidekiq enterprise [rate limiters](https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting) in our application. When they can't acquire a lock in a given amount of time, they raise `Sidekiq::Limiter::OverLimit`, which is rescued by sidekiq's own middleware, and the job is re-enqueued.

The problem is that Appsignal's middleware is sitting lower on the stack (I mean, closer to the code that raises the exception) than sidekiq's own. It sees the exception, treats it as an error (understandably), and then re-raises. So the behavior of the application is fine, but we get flooded with a lot of spurious errors.

We could ignore that particular exception, but rate limiters also have a maximum number of times that they will try to acquire the lock. When `Sidekiq::Limiter::OverLimit` is rescued, if the job has reached is maximum number of retries, then sidekiq does not re-enqueue the job; it gives up. That's a case we very much would like to know about.

Do you have a suggestion for how to handle this? If the Appsignal middleware were on the other side of the middleware that rescues this exception, it would work fine.

**Comment by 97jaz** [comment]
I've added code like the following to an initializer:
```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    if defined?(Appsignal::Hooks::SidekiqPlugin) &&
        chain.exists?(Appsignal::Hooks::SidekiqPlugin)
      chain.remove(Appsignal::Hooks::SidekiqPlugin)
      chain.prepend(Appsignal::Hooks::SidekiqPlugin)
    end
  end
end
```
It does reorder the middleware the way I want it, but it might be a good idea for the Appsignal gem to try to make sure its middleware is at the start of the chain.

**Comment by tombruijn** [comment]
Hi @97jaz ,

Thanks for reporting this issue and coming up with a fix! We're going to look at it and see if we can implement this :)

**Comment by phoet** [comment]
i just started using sidekiq-scheduler and suddenly errors stopped appearing in appsignal. does not look like the scheduler is actually a middleware, but maybe there is a common extension-point where appsignal tries to hook in?

**Comment by PhilCoggins** [comment]
Any progress on this one? We got bit by this today, had some exceptions in third-party middleware and didn't catch them for a while.

**Comment by thijsc** [comment]
Sorry for the slow response on this. We're putting this on our backlog.

**Comment by mperham** [comment]
Part of the issue here is that you aren't using Sidekiq's global error handling system, introduced in Sidekiq 3.0[1]. Unless I'm missing something else, errors within Sidekiq but outside of your middleware won't be reported to AppSignal. Is that the root issue?

1: https://github.com/mperham/sidekiq/blob/master/3.0-Upgrade.md#error-service-providers

**Comment by tombruijn** [comment]
I've released the middleware prepend in Ruby gem version 2.11.6.

We're going to look at the the error handler next, thanks for the insight @mperham !
