### ISSUE TITLE
Custom integer tags for increment_counter not working

### ISSUE THREAD

**Issue by woolfred** [appsignal/appsignal-ruby#529]
Hey there!
We are using `increment_counter` to also log some tags (version 2.9.7).
While creating a dashboard we saw some weird metric names. After tinkering around a bit we narrowed it down and figured out that integers as values for tags are evil.

So by doing:
`Appsignal.increment_counter("custom_metric", 1, integer: 1)` we get following metric key: `{"__name__":"custom_metric","integer":1}`

While `Appsignal.increment_counter("custom_metric", 1, integer: "1")` works as expected and adds a `custom_metric` key.

Looking forward to see a fix for the use of integers. Maybe this is something worth noting in the docs in the meantime.

Cheers!

**Comment by tombruijn** [comment]
Hi @woolfred,

I can reproduce the problem. There must be going something wrong with the JSON parsing of that string for some reason. We're going to look into it!

**Comment by jvanbaarsen** [comment]
Also mentioned in [intercom](https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/2788926/conversations/22629713555) (Private link)

**Comment by matsimitsu** [comment]
This issue has been fixed server-side :)
