### ISSUE TITLE
Minutely probes thread doesn't (re)start if Puma daemonizes

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#530]
When Puma daemonizes (`daemonize true` in `puma.rb` or using `--daemon` on the command line) it starts a new master process by forking the original master process. When the new master process starts it doesn't (re)start AppSignal and the minutely probe thread. This is because we hook into the Puma CLI class which doesn't load if the Rails app isn't started through the Puma CLI `pumactl`.

- `rails server` - doesn't work
- `pumactl start` - works from what I can remember
- `puma` - may not work
- `puma --daemon` - does not work

https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/search/conversations/21871780911

## Workaround

```ruby
# puma.rb

before_fork do
  Appsignal::Minutely.start
end
```

**Comment by tombruijn** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/22235677747

**Comment by tombruijn** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540709/conversations/22424268484

**Comment by matsimitsu** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/14894/conversations/22505662294

**Comment by matsimitsu** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/14894/conversations/22538401802

**Comment by tombruijn** [comment]
Should be fixed in version 2.9.10 of the Ruby gem.
