### ISSUE TITLE
Is there a way to ignore errors for a particular user?

### ISSUE THREAD

**Issue by jerryclinesmith** [appsignal/appsignal-ruby#535]
We have a white hat security firm that tests our site a few times a week, generating lots of errors.  They use a particular user, so we'd like to ignore any errors for this user.  I've looked through the documentation, but don't see a way to do this.

**Comment by tombruijn** [comment]
Hi @jerryclinesmith !

Can you contact us at support@appsignal.com so we can discuss the details with you?

**Comment by jerryclinesmith** [comment]
Will do, thanks
