### ISSUE TITLE
Deprecate the old front-end monitoring Rack middleware

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-ruby#564]
As we now have a fully-fledged front-end monitoring solution now, we can begin to deprecate the old code used for front-end error tracking in the Ruby gem.

## TODO

- [x] Ruby gem: Add deprecation message (STDOUT and appsignal.log) in the when the frontend middleware is loaded / config option is used.
  - Link to the docs for the JavaScript front-end solution
 - [ ] Add message to readme

**Comment by tombruijn** [comment]
Same for the Elixir one https://github.com/appsignal/appsignal-server/pull/4954
I need to add a warning to the README and maybe release a new version that prints a deprecation warning too.

**Comment by xadamy** [comment]
@tombruijn Opened a new issue in `appsignal-elixir` for the Elixir part.

**Comment by tombruijn** [comment]
@xadamy Did you have a timeline for this in mind? We can tell people to switch to the JavaScript integration, right? I already deprecated my [Elixir plug](https://github.com/tombruijn/appsignal-elixir_js_plug)

This looks like a change I would want to ship in the next minor release of the Ruby gem and mention our new JavaScript front-end error reporting solution in the deprecation warning and blog post.

**Comment by xadamy** [comment]
@tombruijn Ready to proceed with this when you are.

> This looks like a change I would want to ship in the next minor release of the Ruby gem and mention our new JavaScript front-end error reporting solution in the deprecation warning and blog post.

100% agreed, ping me if you need a hand with any of these tasks. 👍

**Comment by tombruijn** [comment]
I'm moving it to "planned" then. It looks like a 5 min task, tests included, so might be something I pick up at 16:00 on an unfocused afternoon. Will let you know when a Ruby minor release is planned and this hasn't been picked up yet.

**Comment by tombruijn** [comment]
Deprecated in #572
