### ISSUE TITLE
Markers, Samples, Graphs API

### ISSUE THREAD

**Issue by mbirman** [appsignal/appsignal-ruby#567]
As far as I understand there is no support for the [the API endpoints](https://docs.appsignal.com/api/). Do you consider adding it?

**Comment by tombruijn** [comment]
Hi @mbirman !

This Ruby gem doesn't include methods to consume our API. This gem is only to integrate your apps with it and send data to our [Push API](https://docs.appsignal.com/appsignal/terminology.html#push-api) (which is different from the API you linked). We don't have gems/libraries to call the APIs you linked.

We're working on building a GraphQL API which makes even more data available. That can be found at https://appsignal.com/graphql, which responds to a GraphQL request with a valid user-specific API token, which can be found here: https://appsignal.com/graphql

**Comment by mbirman** [comment]
Hey @tombruijn, thanks for the quick reply!

Too bad there is no library for the API, I was going to use it to collect error statistics across different apps inside an organization. The link you provided leads to a 404 page btw, I suppose the API is not available at the moment?

**Comment by tombruijn** [comment]
@mbirman ah that last link should have been: https://appsignal.com/users/edit
The API is available, but needs [GraphQL](https://graphql.org/) requests to return something. You can see how we use the API on AppSignal.com by checking the requests in the network tab of your browsers web inspector. The GraphQL API also has documentation itself for fields.

**Comment by mbirman** [comment]
Ah, makes sense now. Thank you!

**Comment by tombruijn** [comment]
Great! Closing this issue then.
