### ISSUE TITLE
Why appsignal install exists but appsignal uninstall - not?

### ISSUE THREAD

**Issue by okliv** [appsignal/appsignal-ruby#574]
Try to find information how to delete this software after an installation. Wish you luck!
<img width="430" alt="shot_041" src="https://user-images.githubusercontent.com/884634/70043164-b0148a00-15c8-11ea-8133-ba2b7fa73144.png">

Feature request: add uninstallation script

Question: how to delete this software? I think it is not very pleasant to skip this information just giving some abstract recommendations like this:

<img width="706" alt="shot_042" src="https://user-images.githubusercontent.com/884634/70043455-287b4b00-15c9-11ea-898f-8d40b93a8cba.png">

i don't remember account credentials and do not want to restore it. i just want your software leave my servers, c-mon!

**Comment by mbirman** [comment]
Just curious, what steps of the process do you find too abstract?

**Comment by jvanbaarsen** [comment]
@okliv Thank you for letting us know that this information feels hidden away.  In order to improve this, can you tell me what your expectations were when looking for this information?

Also more importantly, did you find the correct information, or do you need help with this?

**Comment by okliv** [comment]
- what is elixir package? (it's from Harry Potter? :) )... i didn't install it
- remove any configuration... any? how many did `appsignal install` installed it and where? should i grep all my files?
- `appsignal-agent`... don't remember i installed it too [So simple installation](https://github.com/appsignal/appsignal-ruby#installation)
- necessity to login to appsignal.com looks not very pleasant too just because there can be more than one person around an app that earlier used/tried an Appsignal and previous one didn't left that credentials (or more general, access to registered email was lost)

and in general: there is so simple installation steps but it is much more difficult (just counting steps...) to delete it. not very fair, in my opinion

**Comment by okliv** [comment]
And here is NewRelic instructions, for example:
<img width="652" alt="shot_043" src="https://user-images.githubusercontent.com/884634/70045630-18656a80-15cd-11ea-8b31-feb9bd0d365b.png">

S - simplicity.

**Comment by tombruijn** [comment]
Hi @okliv,

Thanks for pointing out that we're not using the "uninstall" keyword in our docs. I've created a PR on our docs to split it per language so people don't get confused about Elixir, Ruby and other potions and gemstones.

> necessity to login to appsignal.com looks not very pleasant too just because there can be more than one person around an app that earlier used/tried an Appsignal and previous one didn't left that credentials (or more general, access to registered email was lost)

You only need to sign in to AppSignal if you want to delete the data we've stored about your application. If you don't the data will automatically be deleted at the end of your [plan's retention](https://appsignal.com/plans).

If you need any help removing AppSignal, don’t hesitate to contact us on contact@appsignal.com.
