### ISSUE TITLE
Use Module.prepend for new instrumentation

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#603]
Fixed in https://github.com/appsignal/appsignal-ruby/pull/683

## Background
The issue reported in #583, causing SystemStackError errors, is because the `http_logger` gem uses `Module.prepend` to monkeypatch the Net::HTTP standard library. This is incompatible with the "method aliasing" method we use in the AppSignal Ruby gem to monkeypatch methods.

We updated the monkeypatch method for the Net::HTTP integration in #597 to use `Module.prepend` for newer Ruby versions, while supporting Ruby 1.9. This was released in Ruby gem version 2.10.5.

The fix in #597 was reverted in PR #604 and released in Ruby gem 2.10.7.

## The problem

However, using the `Module.prepend` method to monkeypatch, breaks compatibility with other libraries that use the "method aliasing" method, such as New Relic, Skylight and Airbrake, as reported in the comments in https://github.com/appsignal/appsignal-ruby/pull/597#issuecomment-622379707 and https://github.com/appsignal/support/issues/71 (private issue)

We probably can't support every method now and in the future, but I think we should move towards the `Module.prepend` solution rather than "method aliasing" if at all possible.

## Potential solution

To support Ruby 1.9 and maintain compatibility with other gems we could introduce a "legacy/compatibility mode" that uses the "method aliasing" method.

For example:

```yaml
# config/appsignal.yml
default: &defaults
  legacy_mode: true

production:
  <<: *defaults
```

```ruby
# lib/appsignal/hooks/net_http.rb
def install
  if Appsignal.legacy_mode? # For Ruby 1.9 and `legacy_mode: true`
    Net::HTTP.class_eval do
      # Method aliasing
      alias request_without_appsignal request

      def request(...)
        Appsignal.instrument(...) do
          request_without_appsignal(...)
        end
      end
    end
  else
    # Module.prepend
    require "appsignal/integrations/net_http"
    Net::HTTP.send(:prepend, Appsignal::Integrations::NetHttpIntegration)
  end
end
```

**Comment by irisbune** [comment]
You might have already seen it, but to be sure: NewRelic says this about it: 
https://docs.newrelic.com/docs/agents/ruby-agent/troubleshooting/systemstackerror-stack-level-too-deep

>Cause
When your app uses Module#prepend on a method that the Ruby agent later uses an alias_method on, it creates a non-terminating recursion and throws the SystemStackError: stack level too deep error.
If you upgraded to Rails 5, which deprecated alias_method_chain, you might have replaced alias_method with Module#prepend, and that could be the source of your issue.

**Comment by tombruijn** [comment]
We're getting more reports of issue with the change in #597. I'm thinking of reverting the change and fix the issue in #583 another time, like in the next minor version.

**Comment by tombruijn** [comment]
I just released Ruby gem 2.10.7 with the revert of this PR #597. Please upgrade to that and let me know if the SystemStackError still occurs. I'll keep this issue open to further discuss if it's possible in the future to move to Module.prepend or not.

**Comment by jkgraham** [comment]
We are also seeing the `stack level too deep` issue with Bugsnag (>= 6.12.0) and AppSignal (2.10.12) during a capistrano deployment (to any environment). When we revert Bugsnag back to before they introduced `Module#prepend` - version 6.11.1 - everything works fine. Definitely in favor of have an explicit `legacy_mode` style switch to allow us to control how AppSignal will work with the gems we use (using `prepend` in place of all aliases).

Error we were seeing before reverting to Bugsnag 6.11.1:
```
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/rubygems/path_support.rb:84 expand
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/rubygems/path_support.rb:32 initialize
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/rubygems.rb:383 new
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/rubygems.rb:383 paths
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/rubygems.rb:429 path
lib/bugsnag/stacktrace.rb:51 block in process
lib/bugsnag/stacktrace.rb:22 map
lib/bugsnag/stacktrace.rb:22 process
lib/bugsnag/report.rb:185 block in generate_exception_list
lib/bugsnag/report.rb:181 map
lib/bugsnag/report.rb:181 generate_exception_list
lib/bugsnag/report.rb:51 initialize
lib/bugsnag.rb:77 new
lib/bugsnag.rb:77 notify
lib/bugsnag/integrations/rake.rb:21 rescue in execute
lib/bugsnag/integrations/rake.rb:14 execute
lib/appsignal/hooks/rake.rb:18 execute
lib/bugsnag/integrations/rake.rb:19 execute
lib/appsignal/hooks/rake.rb:18 execute
lib/bugsnag/integrations/rake.rb:19 execute
lib/appsignal/hooks/rake.rb:18 execute
lib/bugsnag/integrations/rake.rb:19 execute
lib/appsignal/hooks/rake.rb:18 execute
...
```

**Comment by aurelien-reeves** [comment]
We are experiencing that kind of issue too when adding datadog http module

The support request a stack trace, here it is :)

```
2020-09-04 11:24:00.181271966 +0200 CEST [web-1] /app/vendor/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:224:in `tracer': stack level too deep (SystemStackError)
2020-09-04 11:24:00.173888309 +0200 CEST [web-1] #<Thread:0x00005557b16c96a8@/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/workers.rb:72 run> terminated with exception (report_on_exception is true):
2020-09-04 11:24:09.685954805 +0200 CEST [web-1] ppsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:24:in `block in request'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/helpers/instrumentation.rb:426:in `instrument'",
"/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.11/lib/appsignal/hooks/net_http.rb:20:in `request'",
"/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.39.0/lib/ddtrace/contrib/http/instrumentation.rb:41:in `request'", ... SNIP
```

**Comment by jeffkreeftmeijer** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700009585

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700008427

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700011598

**Comment by jeffkreeftmeijer** [comment]
The current status of this in the library; we've [reverted](https://github.com/appsignal/appsignal-ruby/pull/604) the patch that switched to `Module.prepend` in the net_http integration, so we're currently using the monkeypatching method everywhere in the AppSignal integration. This makes us incompatible with newer versions of libraries like Datadog and Bugsnag.

I'll second Tom's [proposal](https://github.com/appsignal/appsignal-ruby/issues/603#issue-611726356), where we move to Module.prepend everywhere in the library, but add a compatibility mode. Then we'll use the monkey patching method for Ruby 1.9 and when compatibility mode is enabled.

The hooks that use method aliasing:

```
lib/appsignal/hooks/action_cable.rb
lib/appsignal/hooks/active_support_notifications.rb
lib/appsignal/hooks/celluloid.rb
lib/appsignal/hooks/net_http.rb
lib/appsignal/hooks/puma.rb
lib/appsignal/hooks/rake.rb
lib/appsignal/hooks/redis.rb
lib/appsignal/hooks/resque.rb
lib/appsignal/hooks/unicorn.rb
lib/appsignal/hooks/webmachine.rb
lib/appsignal/integrations/object.rb
lib/appsignal/integrations/padrino.rb        
lib/appsignal/integrations/que.rb                                                                                                                                                                      
```

**Comment by tombruijn** [comment]
> I'll second Tom's proposal, where we move to Module.prepend everywhere in the library, but add a compatibility mode. Then we'll use the monkey patching method for Ruby 1.9 and when compatibility mode is enabled.

I've actually changed my mind on this. I'm in favor of Module.prepend. But I wouldn't want to support the old method aliasing method if we decide to go the Module.prepend method. I wouldn't want to support both methods if Module.prepend is the future way to go. We have to also drop Ruby 1.9 support in the same release (a major version bump), because Ruby 1.9 doesn't support Module.prepend. It's time to do that.

The supporting and maintaining of both methods will add a lot of code complexity, that won't be fun to maintain. Those who rely on the old method can use older AppSignal for Ruby gem versions until the issue is fixed in the other conflicting gems.

Then if we run into this issue again, from the other side, let's set out to fix it in those gems/places the issue comes from so everything uses Module.prepend. Otherwise the whole ecosystem of these kinds of gems keep dancing around one another as nothing is compatible anymore.

**Comment by jeffkreeftmeijer** [comment]
I'm 100% in favour of the option to switch to Module.prepend, drop 1.9 support and release version 3.0 of the Ruby gem. I'd suggest feature freezing it at only this to get this release out as soon as possible and moving the other next-release work to 4.0. What do you think, @thijsc?

**Comment by thijsc** [comment]
We are planning to add the spans API in Ruby 3.0. I'm not sure how I feel about doing two major releases in a row. We've historically not bumped it often, maybe people would assume they have to carefully upgrade two times?

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700015880

**Comment by jeffkreeftmeijer** [comment]
As discussed in the integrations call; here's the plan for switching to `Module.prepend`. Any thoughts on this, @tombruijn @thijsc? :)

# Switching to Module.prepend

As explained in https://github.com/appsignal/appsignal-ruby/issues/603#issue-611726356, there are two ways to monkey-patch instrumentation into existing code; namely method aliasing and `Module.prepend`. However, when used together in the same module, they cause `SystemStackErrors`. 

We're currently using method aliasing to keep compatibility with Ruby 1.9, because Module.prepend was introduced in Ruby 2.0. Since other libraries are now moving to Module.prepend, we're getting reports of issues by our customers.

Because of that, we'd like to provide an upgrade path to `Module.prepend`. We'll drop method aliasing and switch to `Module.prepend` completely. In the process, we'll drop support for Ruby 1.9, and we'll bump the integration version to 3.0, as per semantic versioning.

In short, the pitch for 3.0 fill be:

> Version 3.0 of AppSignal for Ruby switches from method aliasing to `Module.prepend` internally, for compatibility with other libraries that patch modules in your applications. Although `Module.prepend` was added to Ruby in 2.0, we've kept using method aliasing to keep compatibility with Ruby 1.9 when we released version 2.0 of AppSignal for Ruby. Our new release drops support for Ruby 1.9.
>
> We'll keep supporting Appsignal for Ruby 2.x for the foreseeable future. If you're using any libraries that are incompatible with `Module.prepend`, you can stay on the older version for now. However, please let us know if you do, as we'd love to help other libraries make the switch too.

Since we're bumping the major, we can remove some previously deprecated methods, as listed in https://github.com/appsignal/appsignal-ruby/issues/202. We'll remove all previously deprecated methods. Since we haven't deprecated the "To be deprecated before v3.0" list yet, we'll move that over to the next release.

**Comment by irisbune** [comment]
Thanks for all the effort guys 😄

**Comment by tombruijn** [comment]
@jeffkreeftmeijer looks good 👍

**Comment by jeffkreeftmeijer** [comment]
While moving all instrumentation over to using Module.prepend, I came across our ["`Object` instrumentation"](https://docs.appsignal.com/ruby/instrumentation/method-instrumentation.html), which uses `alias_method` to monkey-patch methods in generic Ruby objects by adding two methods to the `Object` class.

Instead of rewriting this to use `Module.prepend` (for which I don't see a clear approach just yet), I'd rather deprecate these in 3.0, and write a documentation guide that lays out adding custom instrumentation using Module.prepend yourself, if we get support requests about this. Any objections to that?

**Comment by jeffkreeftmeijer** [comment]
Status update: all of the integrations now run through Module.prepend instead of method aliasing, except for the Padrino one. I wasn't able to get it to override the `route!` method today.

``` ruby
Padrino::Routing.send(:prepend, Module.new {  
  def route!(base = settings, pass_block = nil)  
    raise "KRAK!"
  end  
})
```

Something like this doesn't seem to work, as by the time this code is executed, the routes are already included in the app. I'm not sure if this is caused by the test setup, or the actual integration, but I'll dive in a bit deeper tomorrow. @tombruijn  do you have any insight there? You seem to be the last one to work on this (albeit 4 years ago). 😬

**Comment by tombruijn** [comment]
> Instead of rewriting this to use Module.prepend (for which I don't see a clear approach just yet), I'd rather deprecate these in 3.0, and write a documentation guide that lays out adding custom instrumentation using Module.prepend yourself, if we get support requests about this. Any objections to that?

It may also be less problematic? It's not necessarily something other gems would alias methods for as it's supposed to be used for custom app code. These methods wouldn't cause a conflict also being `Module.prepend`ed. I wouldn't want to deprecate it right away because it's using the alias method.

**Comment by tombruijn** [comment]
> @tombruijn do you have any insight there? You seem to be the last one to work on this (albeit 4 years ago). 😬

Nothing springs to mind no 😬  I would need to dive deeper into it to see why it's going wrong or how to fix it.

**Comment by jeffkreeftmeijer** [comment]
I tried getting through again. Here's a test setup that should work similarly to how Padrino attaches to Sinatra, and how the Router gets added to the Application:

``` ruby
module InstanceMethods              
  def foo                            
    p "FOO!"                                                     
  end                                           
end                                              
                            
module Routing                                               
  class << self                                          
    def registered(app)    
      app.send(:include, InstanceMethods)                                         
    end        
  end                              
end                                                                
                                                                     
class Base                                      
  class << self                                              
    def register(extension)                              
      extend extension    
      extension.registered(self)                    
    end                                                           
  end                      
end                                       
                                                 
InstanceMethods.send(:prepend, Module.new {                    
  def foo    
    raise "PREPENDED!"    
  end                                                
})               
                                                             
class Application < Base                      
  register Routing         
end                    
                                   
Application.new.foo # => PREPENDED!
```

Adding the prepended method here works as long as it's executed before the Application class is defined. Back in the [Padrino hook](https://github.com/appsignal/appsignal-ruby/blob/module-prepend/lib/appsignal/integrations/padrino.rb#L22-L47), I'd say the same code should work, but I'm missing something. @tombruijn, if you have time, could you spend half an hour to look at this? I feel like I'm missing something obvious in this pile of ancestry.

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/16410700020178

**Comment by tombruijn** [comment]
We merged #683 that moves all our integrations to use Module.prepend. This will be shipped in the next major release: 3.0. We don't have a release date yet, but also don't want to wait too long with shipping it.

**Comment by tombruijn** [comment]
We've released a beta release for the 3.0 Ruby gem, `3.0.0.beta.1`. Please help us test the fix for this issue by installing the beta in your app in a non-production environment. Let us know here if you run into any other problems after installing that version. Or let us know at support@appsignal.com!

**Comment by tombruijn** [comment]
I released Ruby gem 3.0.0.rc.1 which will be the version that will be the final release, unless any last minute bugs come up. It's almost identical to beta.1 except for some patch releases in the 2.x series that were merged into the 3.0.0 branch. Please test it and let us know at support@appsignal.com if any issues come up.

**Comment by tombruijn** [comment]
Ruby gem 3.0 is released! Read more about it in [our blog post about the release](https://blog.appsignal.com/2021/03/01/ruby-gem-3-0.html) and [read our upgrade guide to upgrade](https://docs.appsignal.com/ruby/installation/upgrade-from-2-to-3.html).

Do any issues come up, please contact us at support@appsignal.com

**Comment by conarro** [comment]
Just adding a note to this issue for anyone else who encounters the `SystemStackError (stack level too deep)` errors (#583) due to the switch to `prepend`:

We ran into during our v3 upgrade. We got the error from `Net::HTTP` requests (specifically ActiveStorage attachment uploads), and only in the `development` environment. Turns out `rack-mini-profiler` was the culprit. We load that in dev with `require: false`, but you can force the profiler to use `prepend` like so:

```ruby
gem 'rack-mini-profiler', require: ['prepend_net_http_patch']
```

Source: https://github.com/MiniProfiler/rack-mini-profiler#nethttp-stack-level-too-deep-errors

**Comment by shairyar** [comment]
Thank you for sharing your findings 👍🏼
