### ISSUE TITLE
Possible to subscribe to notifications instead of monkey patching Rails?

### ISSUE THREAD

**Issue by ce07c3** [appsignal/appsignal-ruby#635]
I came across a potential issue with the `http` gem and the `appsignal` gem. The `appsignal` gem uses hooks to install itself into other gems, e.g. Rails instrumentation. Is this compatible with the `start` and `finish` way of dealing with instrumentations in Rails? [See this piece of code](https://github.com/httprb/http/blob/master/lib/http/features/instrumentation.rb):

```rb
      def wrap_request(request)
        # Emit a separate "start" event, so a logger can print the request
        # being run without waiting for a response
        instrumenter.instrument("start_#{name}", :request => request) {}
        instrumenter.start(name, :request => request)
        request
      end

      def wrap_response(response)
        instrumenter.finish(name, :response => response)
        response
      end
```

Since `appsignal` doesn't subscribe to the notifications but rather monkey patches Rails, I fear it never catches the notifications fanned out by using `start`/`finish`. I didn't debug too deeply, but it semed as if these events were not arriving in Appsignal.

What I ended up doing:

```rb
# where the HTTP library is used
HTTP.use(
  instrumentation: { 
    instrumenter: ActiveSupport::Notifications.instrumenter, 
    namespace: "namespace" 
  }
)

# in an appsignal initializer, for instance
ActiveSupport::Notifications
  .subscribe(/\Arequest\.namespace\z/) do |name, started, finished, id, payload|
    event = ActiveSupport::Notifications::Event.new(name, started, finished, id, payload)
    title, body, body_format = Appsignal::EventFormatter.format(name, payload)
    Appsignal::Transaction.current.record_event(
      name.to_s,
      title,
      body,
      event.duration,
      body_format
    )
  end
```

**Comment by tombruijn** [comment]
Hi @ce07c3,

I'm not sure, I'll have to test that. There's mention of the fanout active support queue in our test suite, but it's been a while since we touched it, so it's not top of mind.

**Comment by ce07c3** [comment]
I believe the issue is simply with monkey patching when the library could just subscribe to all notifications with the `/.*/` pattern.

**Comment by tombruijn** [comment]
We did in the past, yes. That was changed in #150 after some performance issues with subscribing to all the events that way.

**Comment by ce07c3** [comment]
Well, unfortunately this leads to other issues. Good point about performance issues, I'll check that.

**Comment by jeffkreeftmeijer** [comment]
Hey @ce07c3,

We’ve released version 2.11.1-beta.1, which adds support for ActiveSupport notifiers that use start and finish. Could you try that and let us know how it works for you?

**Comment by ce07c3** [comment]
@jensljungblad something for Friday? :)

**Comment by thijsc** [comment]
2.11.1 has been released in the meantime that should fix this issue.
