### ISSUE TITLE
Rails runner support

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-ruby#641]
Add support for error reporting from inside Rails runners: https://guides.rubyonrails.org/command_line.html#rails-runner

## To do

- [x] Report errors
- [x] Add docs for reporting performance

**Comment by tombruijn** [comment]
@xadamy can you link to the intercom convo that brought this to our attention?

**Comment by xadamy** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700002295

**Comment by raulr** [comment]
As a workaround I add this inside the Application class in `config/application.rb`:

```ruby
runner do
  next unless defined?(Appsignal) && Appsignal.active?

  action_name = ARGV.first&.truncate(50) || "unknown"

  Kernel.at_exit do
    next unless $!

    Appsignal.send_error($!) do |transaction|
      transaction.set_action action_name
      transaction.set_namespace "background"
    end
    Appsignal.stop "runner"
  end
end
```

But this way you only get error reporting, not instrumentation. Official support of rails runner would be great.

**Comment by tombruijn** [comment]
Will be included in Ruby gem 4. Closing.
