### ISSUE TITLE
Shoryuken Crashes when batch option is true

### ISSUE THREAD

**Issue by ecnerwalawrence** [appsignal/appsignal-ruby#661]
When Shoryuken is on batch mode, these code blocks don't work.  In batch mode, `sqs_msg` and `body` are returned as arrays.  Unfortunately, the Appsignal Shoryuken hook expects `sqs_msg` and `body` as objects.

https://github.com/appsignal/appsignal-ruby/blob/096d2858e3aa6e89a786c0416b1210f668faf413/lib/appsignal/hooks/shoryuken.rb#L8

https://github.com/appsignal/appsignal-ruby/blob/096d2858e3aa6e89a786c0416b1210f668faf413/lib/appsignal/hooks/shoryuken.rb#L15

You can merge all the attributes.
```ruby
attributes = sqs_msg.map(:attributes).reduce({},:merge)
```
The body is a little more tricky.  Maybe, you can put it in an array.  

Whatever solution that you choose, it shouldn't crash the worker.  Also, it must be compatible with your existing UI or new UI.  The current code does not allow the worker to startup with batch mode.

**Comment by tombruijn** [comment]
Hi @ecnerwalawrence, Sorry for the very delayed response. This issue slipped through.

I looked at the batch option and found this in the wiki:

> If you are using a custom middleware, check this article, the sqs_msg and body are arrays when batch=true.

https://github.com/phstc/shoryuken/wiki/Worker-options#batch

So it looks like we should expect arrays there, but we do not currently. This looks like a bug.

If you batch these messages, do you expect one sample for all the messages processed, or a sample per processed message?

**Comment by tombruijn** [comment]
@ecnerwalawrence Batch support has just been released in version 2.11.3 of the Ruby gem.

**Comment by ecnerwalawrence** [comment]
> Hi @ecnerwalawrence, Sorry for the very delayed response. This issue slipped through.
> 
> I looked at the batch option and found this in the wiki:
> 
> > If you are using a custom middleware, check this article, the sqs_msg and body are arrays when batch=true.
> 
> https://github.com/phstc/shoryuken/wiki/Worker-options#batch
> 
> So it looks like we should expect arrays there, but we do not currently. This looks like a bug.
> 
> If you batch these messages, do you expect one sample for all the messages processed, or a sample per processed message?

Hmm.  I am impartial on any solution.

**Comment by ecnerwalawrence** [comment]
> @ecnerwalawrence Batch support has just been released in version 2.11.3 of the Ruby gem.

Many thanks!  I'll try it out.

**Comment by tombruijn** [comment]
> > If you batch these messages, do you expect one sample for all the messages processed, or a sample per processed message?
> 
> Hmm. I am impartial on any solution.

Unfortunately I had to go for the route that instruments all messages as one batch. That's how the middleware in shoryuken works and I was limited by that. I couldn't instrument every message in a batch separately. This means the metadata on the sample we collect for a batch will not include the metadata for every message, but only the oldest message as that probably contains the most relevant information: how long ago the message was created and how many times it was retried.
