### ISSUE TITLE
Deprecate (set|send)_error metadata arguments

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-ruby#678]
As [described in the documentation](https://docs.appsignal.com/ruby/instrumentation/exception-handling.html#appsignal-set_error), our error methods have specific arguments for passing metadata like tags and namespaces. Because we also allow a block to be passed, we’d like to switch to using that instead.

We’ll deprecate these arguments and recommend using a block instead.

- [ ] Deprecate method arguments
- [ ] Update docs to recommend using blocks

**Comment by tombruijn** [comment]
Deprecate them in version 3 and drop them in version 4?

**Comment by jeffkreeftmeijer** [comment]
Yes, that sounds like a plan. Let’s triage this to be before the 3.0 release in the next integrations call.
