### ISSUE TITLE
appsignal agent process utilises 100% of CPU when using rails console

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-ruby#696]
When running the rails console on the container, the appsignal-agent process begins to utilize 100%+ of CPU,

The customer using version 2.11.4
Diagnostic report: https://appsignal.com/admin/diagnose_reports/diagdaa54708f6b8b159c6b5
appsignal.log: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700023825#part_id=comment-16410700023825-7789530617

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700023825

**Comment by shairyar** [comment]
The customer is now running into this even when they are not using rails console.

**Comment by tombruijn** [comment]
Thijs says, we read the socket but it's empty, so it keeps retrying very quickly, causing a 100% CPU usage. Let's see if we can add a small sleep in that retry action to avoid the 100% CPU.
It wouldn't solve the communication issue that's occurring here.

**Comment by tombruijn** [comment]
@jeffkreeftmeijer you can also try to set up a similar test setup as for the FreeBSD issue which recreated the mio create issue to try and reproduce it: https://github.com/appsignal/rust-library-mio-freebsd-test-setup
You'll probably need to copy-paste in the code that probably causes it, and run it on a Ubuntu VM probably. This issue is not specific to the FreeBSD OS, the other issue https://github.com/appsignal/support/issues/118 is.

**Comment by shairyar** [comment]
I have another customer who ran into this issue where the usage shoots up and the host metrics load avg shows 0, they are using the latest version of Ruby integration.


Intercom: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700079256
Diagnose report: https://appsignal.com/admin/diagnose_reports/diag78b5be17f88bf3e70375

I am also seeing the same error in their report which I see in the report of a customer who reported this issue earlier.

```
[2021-12-13T23:59:59 (agent) #10][Error] Error getting disk IO stats: No such file or directory (os error 2) for /proc/diskstats
[2021-12-14T00:00:00 (agent) #10][Error] Error getting disk IO stats: No such file or directory (os error 2) for /proc/diskstats
```

**Comment by luismiramirez** [comment]
After a chat with @thijsc, this is due to a bug from `mio` Rust crate.

We'll cover it with https://github.com/appsignal/appsignal-agent/issues/708

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700090078

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700105029

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700105480

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/16410700116700

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700132061

**Comment by tombruijn** [comment]
@shairyar do you need to follow up with the following conversations, or can we close the issue?

- https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700116700 / https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700105480
- https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700079256

**Comment by shairyar** [comment]
This can be closed
