### ISSUE TITLE
Handled exceptions from ActiveJob are still reported to AppSignal

### ISSUE THREAD

**Issue by nickcampbell18** [appsignal/appsignal-ruby#710]
## Describe the bug

ActiveJob in Rails lets the user specify errors that they would like to automatically retry, with the [retry_on](https://api.rubyonrails.org/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-retry_on) method. From the documentation (emphasis mine):

> Catch the exception and reschedule job for re-execution after so many seconds, for a specific number of attempts. If the exception keeps getting raised beyond the specified number of attempts, **the exception is allowed to bubble up to the underlying queuing system**, which may have its own retry mechanism or place it in a holding queue for inspection.

I've had a read through the hooks code but I don't think that the AppSignal client is looking at these handlers. For us, the upshot is that when this known & expected exception occurs in our app, we're still getting an error report from AppSignal, which isn't helpful (as the job will always succeed on the second attempt).

This might not be a bug, it might be intended behaviour, in which case is there a reasonable way to opt-out of these exceptions? Unfortunately, we're rescuing a fairly generic `ActiveRecord::RecordNotUnique` exception in our case, which we don't want to suppress across the whole application, just in these specific worker jobs.

## To Reproduce

- Using AppSignal for Ruby gem version v3.0.1
- In my app using activejob v6.1.3
- With this code:
  ```ruby
  class MyJob < ActiveJob::Base
    retry_on ActiveRecord::RecordNotUnique, wait: 1.second, attempts: 1

    def perform
      raise ActiveRecord::RecordNotUnique
    end
  end
  ```

_Expected behaviour:_ when the job raises `ActiveRecord::RecordNotUnique` the first time, ActiveJob will requeue the job, and no error message is emitted. If it fails the second time, we'd expect an AppSignal error notification

_Actual behaviour:_ the first time that the job fails, we get an AppSignal notification

**Comment by tombruijn** [comment]
Hi @nickcampbell18,

What you're describing is correct. We report all errors, even if the job gets retried. Our ActiveJob integration is reporting errors that occur in any ActiveJob job.

We agree that we could do better reporting or notifications based on the retry attempts. Either not send the errors if they are going to be retried, or only send out notifications if the maximum number of retries have been reached.

For now, it's not possible to ignore an error only once, other than catch the error and raise a custom error of sorts if the maximum retry attempts have not been reached yet.

I'm going to close this issue and create a feature request on our private tracker to further explore the approach we would want for this and how we can best apply this to all our integrations.

**Comment by nickcampbell18** [comment]
Thanks for the thoughful response, much appreciated 🙏
