### ISSUE TITLE
No HTTP requests traced from http.rb gem

### ISSUE THREAD

**Issue by robinvdvleuten** [appsignal/appsignal-ruby#770]
## Describe the bug

Any request made through the [http.rb](https://github.com/httprb/http) gem are not traced / visible on Appsignal. Any request made through `request.net_http` does.

## To Reproduce

- Using AppSignal for Ruby gem version 3.0.15
- In my app using framework/library/gem http version 5.0.4
- With this code:
  ```rb
  response = HTTP.timeout(10).headers('User-Agent' => '***').post(webhook.url, json: delivery)
  raise UnsuccessfulResponseError if response.status.server_error?
  ```

**Comment by robinvdvleuten** [comment]
So as I look through the appsignal hooks, it seems that only libraries that wrap `net_http` are supported.

**Comment by tombruijn** [comment]
Hi @robinvdvleuten, we don't support the http gem if it doesn't use net_http. We'll put it on our backlog to look at.
