### ISSUE TITLE
Deprecate skip_session_data in favor of send_sessison_data

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-ruby#802]
As stated in appsignal/integration-guide#114, skip_session_data is an inconsistent name among other similar options.

Deprecate skip_session_data config option and add send_session_data instead. Note that the boolean values now work the other way around as the new option works in "positive"

When skip_session_data is set up, log a deprecation message.

**Comment by tombruijn** [comment]
Added docs in https://github.com/appsignal/appsignal-docs/pull/533. Closing.
