### ISSUE TITLE
Ruby version 2.6 not working

### ISSUE THREAD

**Issue by ErinStearns** [appsignal/appsignal-ruby#809]
Is there a solution to this problem besides upgrading/downgrading from 2.6 (which seems silly)? 

src: https://docs.appsignal.com/support/known-issues/ruby-2-6-extension-not-installing.html

**Comment by tombruijn** [comment]
Hi @ErinStearns, in newer versions for the AppSignal Ruby gem the issue you link to is fixed. What version of the AppSignal Ruby gem are you using? Are you able to upgrade it to the latest version?

**Comment by tombruijn** [comment]
I'm closing this issue for now. You can also contact us at support@appsignal.com if this issue is still present in newer Ruby gem versions.
