### ISSUE TITLE
Nested instrumentation doesn't works with threads

### ISSUE THREAD

**Issue by nicolasgarnil** [appsignal/appsignal-ruby#837]
## Describe the bug

Nested instrumentation doesn't works with threads. The traces sent from inside the thread are ignored and not displayed in the Event Timeline.

## To Reproduce

Steps to reproduce the behaviour:

- Using AppSignal for Ruby gem version 3.0.20
- With this code:

```ruby
Appsignal.instrument("a.xxx") do
  Appsignal.instrument("b.xxx") do
     5.times do
       Thread.new do
         Appsignal.instrument("c.xxx") do
           # do stuff
         end
       end
    end
  end
end
```

We would expect to see this:

* a.xxx
  * b.xxx
    * c.xxx
    * c.xxx
    * c.xxx  
    * c.xxx  
    * c.xxx  

Instead we see:

* a.xxx
  * b.xxx

**Comment by shairyar** [comment]
Hi Nicolas, this is not possible at the moment. Our current API keeps track of transactions per Thread and doesn't support multiple threads at the moment. We're working on supporting this in the future, but we have no ETA for this yet.

**Comment by tombruijn** [comment]
This is a known issue. I'm closing it for now.
