### ISSUE TITLE
appsignal client causes a 100% cpu usage when the ruby garbage collector runs a cycle

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-ruby#846]
The appsignal client causes the 100% CPU when the ruby garbage collector runs a cycle? Enabling GC via GC.enable had the same effect.

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700105480

**Comment by shairyar** [comment]
Latest follow up: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700116700

> Hi folks. Do you perhaps have any further info regarding the appsignal client going to 100% cpu when the ruby garbage collector runs a cycle? I explicitly enabled GC in our application (via GC.enable) which had the same effect. So now I'm in between a rock and a hard place: 100% memory or 100% CPU.

**Comment by luismiramirez** [comment]
They were using an EOL version of Ruby (2.6.6), and after the upgrade to 2.7.6 the issue stopped. We can consider this one solved.
