### ISSUE TITLE
Improve error handling in Rails instrumentation

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#851]
In https://github.com/appsignal/support/issues/201#issuecomment-1168532829 I explain the situation in more detail, but in short:

When calling `ActionDispatch#request_method` an error can be raised when an unknown request method is trying to be parsed. We don't expect [that method to raise an error in our Rails instrumentation](https://github.com/appsignal/appsignal-ruby/blob/114fe4f92e621bc2e771bb0fb608b5c6189f2933/lib/appsignal/rack/rails_instrumentation.rb#L43).

We need to add error handling to that method call and do not set the request method on the transaction if an error is raised. The error from `ActionDispatch#request_method` can be ignored as the request probably already encountered it and the transaction is about that very same error.

## To do

- [x] Add error handling to [`ActionDispatch#request_method` method call in Rails instrumentation](https://github.com/appsignal/appsignal-ruby/blob/114fe4f92e621bc2e771bb0fb608b5c6189f2933/lib/appsignal/rack/rails_instrumentation.rb#L43).
  Something like:
  ```ruby
  begin
    transaction.set_metadata("method", request.request_method)
  rescue
    # Do nothing
  end
  ```
- [x] Add testing for this scenario.
- [x] Check if this problem can occur in any other places like our rack and sinatra 
integrations.
  - Rack and Sinatra return `nil` instead.
    ```
    >> require "rack"
    => true
    >> Rack::Request.new(:method => "foo").request_method
    => nil

    >> require "sinatra"
    => true
    >> Sinatra::Request.new(:method => "foo").request_method
    => nil
    ```

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700127439 (Private link)
