### ISSUE TITLE
SystemStackError when used with httplog gem

### ISSUE THREAD

**Issue by prognostikos** [appsignal/appsignal-ruby#880]
We occasionally use the `httplog` gem to troubleshoot various API integrations. If we try to use it (via `require 'httplog'`) when appsignal is active, we get a `SystemStackError` when making HTTP calls using `Net::Http`.

## To Reproduce

- Using AppSignal for Ruby gem version 3.1.4
- In my app using httplog version 1.5.0
- With this code:

```
  [2] prod:(main)> r = Net::HTTP.get_response(URI('https://appsignal.com'))
=> #<Net::HTTPMovedPermanently 301 Moved Permanently readbody=true>
[3] prod:(main)> require 'httplog'
=> true
[4] prod:(main)> r = Net::HTTP.get_response(URI('https://appsignal.com'))
D, [2022-08-16T10:10:00.270837 #4] DEBUG -- : [httplog] Connecting: appsignal.com:443
SystemStackError: stack level too deep
from /app/vendor/bundle/ruby/2.7.0/gems/appsignal-3.1.4/lib/appsignal/integrations/net_http.rb:9:in `request'
[5] prod:(main)> wtf
Exception: SystemStackError: stack level too deep

0: /app/vendor/bundle/ruby/2.7.0/gems/appsignal-3.1.4/lib/appsignal/integrations/net_http.rb:9:in `request'
1: /app/vendor/bundle/ruby/2.7.0/gems/httplog-1.5.0/lib/httplog/adapters/net_http.rb:12:in `block in request'
2: /app/vendor/ruby-2.7.6/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
3: /app/vendor/bundle/ruby/2.7.0/gems/httplog-1.5.0/lib/httplog/adapters/net_http.rb:11:in `request'
4: /app/vendor/bundle/ruby/2.7.0/gems/appsignal-3.1.4/lib/appsignal/integrations/net_http.rb:11:in `block in request'
```

**Comment by tombruijn** [comment]
Hi @prognostikos, this can happen if the httplog gem uses a certain way of adding its own logic to the net_http library. We've written about this in our [upgrading AppSignal Ruby gem version 2 to 3 in our docs](https://docs.appsignal.com/ruby/installation/upgrade-from-2-to-3.html#compatibility-with-other-instrumentation-gems).

What's happening here is that in AppSignal Ruby gem 3.x we made the change from using method aliasing to adding instrumentation to certain methods, to using the `Module.prepend` method. These two instrumentation methods are incompatible.

We've chosen to change our instrumentation to use the `Module.prepend` method as more APM and instrumentation libraries made a similar change, so we'd be compatible when multiples of these gems are present in your app. Not all instrumentation libraries, like httplog, will be compatible. We have to choose one way or the other, and `Module.prepend` seems like the better approach.

For why it's happening in the httplog gem, you can see that they are [aliasing methods for the Net::HTTP library](https://github.com/trusche/httplog/blob/e57a8624b19f38956d75c14945eecdf3495b9051/lib/httplog/adapters/net_http.rb#L5-L6). We've instead [created a new module with a `request` method](https://github.com/appsignal/appsignal-ruby/blob/0a1ad807ac0c57b414905988e7b5dd6996bbed44/lib/appsignal/integrations/net_http.rb#L6) and [prepended it in the Net::HTTP module](https://github.com/appsignal/appsignal-ruby/blob/0a1ad807ac0c57b414905988e7b5dd6996bbed44/lib/appsignal/hooks/net_http.rb#L17). These two methods are incompatible.

We recommend httplog either changes their logging to use Module.prepend. The Module.prepend method would look something like this:

```diff
diff --git httplog/lib/httplog/adapters/net_http.rbhttplog/lib/httplog/adapters/net_http.rb 
index 315bbed..14e2355 100644
--- httplog/lib/httplog/adapters/net_http.rb
+++ httplog/lib/httplog/adapters/net_http.rb
@@ -1,13 +1,10 @@
-module Net
-  class HTTP
-    alias orig_request request unless method_defined?(:orig_request)
-    alias orig_connect connect unless method_defined?(:orig_connect)
-
+module HttpLog
+  module NetHttpLogger
     def request(req, body = nil, &block)
       url = "http://#{@address}:#{@port}#{req.path}"

       bm = Benchmark.realtime do
-        @response = orig_request(req, body, &block)
+        @response = super
       end
       body_stream  = req.body_stream
       request_body = if body_stream
@@ -42,7 +39,9 @@ def request(req, body = nil, &block)
     def connect
       HttpLog.log_connection(@address, @port) if !started? && HttpLog.url_approved?("#{@address}:#{@port}")

-      orig_connect
+      super
     end
   end
 end
+
+Net::HTTP.send(:prepend, HttpLog::NetHttpLogger)
```
I could even try to send this in as a PR if it's not too much work, but it would make the Net::HTTP logger work differently from all the other adapters.

**Comment by tombruijn** [comment]
@prognostikos I just remembered you can also use the [instrument_net_http config option](https://docs.appsignal.com/ruby/configuration/options.html#option-instrument_net_http) to disable our Net::HTTP instrumentation and avoid this error.

```
# Example: config/appsignal.yml
default: &defaults
  instrument_net_http: false
```

**Comment by prognostikos** [comment]
@tombruijn thanks for the quick and detailed response.
