### ISSUE TITLE
Development mode logging in Rails

### ISSUE THREAD

**Issue by thijsc** [appsignal/appsignal-ruby#908]
It was reported that ActiveRecord queries don't show up in logs when an app is running in development/staging mode. This should be off by default because of leaking of sensitive information, but can be useful when running in development mode. It appears Rails has some way of preventing the queries from being sent.

I reproduced this by adding a logger to https://github.com/appsignal/test-setups/tree/main/ruby/rails7-sidekiq, but did not commit that.

Reported here: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/14888/conversations/16410700163180

**Comment by thijsc** [comment]
This docs issue might be related: https://github.com/appsignal/appsignal-docs/issues/989. I think it might be a similar thing that Rails uses.

**Comment by jeffkreeftmeijer** [comment]
@thijsc could you push that logger you added to the test-setups in a branch somewhere?

**Comment by thijsc** [comment]
I didn't commit it, it was something like `Rails.logger = AppSignal::Logger.new` in `application.rb`.

**Comment by jeffkreeftmeijer** [comment]
I tried reproducing this by [adding a `UsersController`](https://github.com/appsignal/test-setups/commit/1df2305cac6989add825c63a5084144e75f37ac8) and[ setting up logging](https://github.com/appsignal/test-setups/commit/98211f5346f924d47cc9409887ee48d6c92374f7) in [a Rails 7 test app](https://github.com/appsignal/test-setups/tree/development-logging/ruby/rails7-sidekiq), but was unable to. Requesting the user index produces the following logs in AppSignal:


```
18-01-2023 15:12:26.000[application][INFO][MacBook-Pro-3.local][rails]Started GET "/users" for 127.0.0.1 at 2023-01-18 15:12:26 +0100
+18-01-2023 15:12:26.000[application][INFO][MacBook-Pro-3.local][rails] Rendered layout layouts/application.html.erb (Duration: 6.4ms | Allocations: 2337)
+18-01-2023 15:12:26.000[application][DEBUG][MacBook-Pro-3.local][rails] [1m[36mUser Load (0.3ms)[0m [1m[34mSELECT "users".* FROM "users"[0m
+18-01-2023 15:12:26.000[application][INFO][MacBook-Pro-3.local][rails]Processing by UsersController#index as */*
+18-01-2023 15:12:26.000[application][INFO][MacBook-Pro-3.local][rails]Completed 200 OK in 9ms (Views: 6.9ms | ActiveRecord: 0.3ms | Allocations: 2578)
```

![Image](https://user-images.githubusercontent.com/43621/213193961-723d5500-1aca-40a8-a1d3-2dd6c11cfa13.png)

**Comment by thijsc** [comment]
Just chiming in to emphasise that this is only safe to use in development mode with non-production data.

**Comment by tombruijn** [comment]
My guess is what we're seeing is `config.active_record.verbose_query_logs = true` on development being on, but those logs are not sent to the actual logger. I don't see these queries being logged the environment's log file.

For example, making a request shows this in the Rails process output:

```
Started GET "/queries" for 192.168.65.1 at 2023-11-01 15:23:23 +0000
Cannot render console from 192.168.65.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  Rendering layout layouts/application.html.erb
  Rendering examples/queries.html.erb within layouts/application
  User Load (1.1ms)  SELECT "users".* FROM "users"
  ↳ app/views/examples/queries.html.erb:11
  Rendered examples/queries.html.erb within layouts/application (Duration: 57.3ms | Allocations: 28049)
  Rendered layout layouts/application.html.erb (Duration: 155.1ms | Allocations: 72019)
```

And this is logged to the Rails development log:

```
Processing by ExamplesController#queries as HTML
Completed 200 OK in 183ms (Views: 157.1ms | ActiveRecord: 3.3ms | Allocations: 81826)
```

**Comment by tombruijn** [comment]
With a bunch of additional config I got it to work:

```
# config/application.rb
Rails.application.configure do
  # other config...
  config.log_level = :debug
  config.colorize_logging = false # This is just better for log files, but also disables it in the Rails server process output 🤷‍♂️
end

# initializers/logging.rb
console_logger = ActiveSupport::Logger.new(STDOUT)
console_logger.level = Logger::DEBUG
# Extra log file to compare the standard log file. This `development-custom.log` actually contains the queries in the log file, the standard `development.log` does not.
file_logger = ActiveSupport::Logger.new(Rails.root.join("log", "#{Rails.env}-custom.log"))
file_logger.level = Logger::DEBUG
appsignal_inner_logger = Appsignal::Logger.new("rails")
appsignal_inner_logger.level = Logger::DEBUG
appsignal_logger = ActiveSupport::TaggedLogging.new(appsignal_inner_logger)

Rails.application.config.log_tags = [:request_id]
Rails.logger = ActiveSupport::BroadcastLogger.new(console_logger, appsignal_logger, file_logger)

```

![image](https://github.com/appsignal/appsignal-ruby/assets/282402/5f2f912f-bbbf-4843-b5e4-5f3fee724725)

**Comment by tombruijn** [comment]
Informed user. Closing.
