### ISSUE TITLE
Instrument Hanami using dry-monitor

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-ruby#910]
Timebox: 1 day (for research)

As mentioned by Peter Solnica in [this toot](https://ruby.social/@solnic/109614838390721996), Hanami 2 uses [dry-monitor](https://github.com/dry-rb/dry-monitor) by default. A gem like `ActiveSupport::Notifications` to monitor and instrument in Ruby.

The current integration is made by monkey patching `Hanami::Action`. Using dry-monitor would allow us to remove such monkey patch.

## To do

~~- [ ] Add a listener for dry-monitor to our Ruby gem~~
~~- [ ] Test the data that is reported is useful, and report back if we are missing some data to Peter~~
~~- [ ] If we have enough data, ship the dry-monitor listener~~
- [x] Add a hook for dry-monitor instrumentation
- [x] Format rom-sql events that go through dry-monitor 
- [ ] Update documentation

**Comment by luismiramirez** [comment]
The dry-monitor rack instrumentation doesn't provide all the data we need.

Added a hook for `dry-monitor` similar to the one we have for `ActiveSupport::Notifications` and native support for `rom-sql` events.

**Comment by tombruijn** [comment]
https://discourse.rom-rb.org/t/adding-the-rom-suffix-to-emitted-events/599/4
