### ISSUE TITLE
Collecting HTTP request paths 

### ISSUE THREAD

**Issue by richardboehme** [appsignal/appsignal-ruby#915]
Hey!

We are currently integrating AppSignal into an app of one of our clients. As we are communicating heavily with a 3rd-party backend-API over HTTP we wondered why monitored HTTP requests (via Net::HTTP or HTTP.rb) do not contain the full path but only the requested host. Some requests to our application have to do multiple requests at the described API so it would be useful to differentiate between the requests when looking at a performance sample.

As ActiveRecord and ElasticSearch queries are collected as well we think this change would fit into the gem. What do you think? If you agree we could help implementing this feature.

P.S.: Not sure if the issue type is correct. This does not really fit in any of the two categories.

**Comment by tombruijn** [comment]
Hi @richardboehme,

We chose not to implement for a couple reasons. Our backend prefers grouped events based on the event category, title and body. If those are too unique between events, we generate a lot of data and things become slower. PII is another thing to watch out for, it would need to make sure not sensitive data gets sent to our servers.

We may revisit this when we change over our Ruby gem to our newer backend, but for now don't want to change this.

**Comment by richardboehme** [comment]
> Hi @richardboehme,
> 
> We chose not to implement for a couple reasons. Our backend prefers grouped events based on the event category, title and body. If those are too unique between events, we generate a lot of data and things become slower. PII is another thing to watch out for, it would need to make sure not sensitive data gets sent to our servers.
> 
> We may revisit this when we change over our Ruby gem to our newer backend, but for now don't want to change this.

Thanks for the info! I totally understand although I wonder why stuff like ES queries and ActiveRecord queries are fine but maybe those are more relevant to the majority of people. Looking forward to the new backend for Ruby :smile:
