### ISSUE TITLE
Don't activate AppSignal when the configuration file fails to load

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#926]
When the configuration file `config/appsignal.yml` fails to load (a YAML or ERB error occurs while parsing), do not start AppSignal. Even if it has a valid config based on configuration from other sources (like the initial config and environment variables).

Discussed in:
- https://github.com/appsignal/appsignal-ruby/pull/925
- [Internal Slack discussion](https://appsignal.slack.com/archives/CNPP953E2/p1678877487388849)

## To do

- [x] Find a good way to deactivate AppSignal when an error was encountered during the config file (`config/appsignal.yml`) loading and parsing. For example: Use the `override` config source and add `active: false` to it?
- [x] If necessary, mark this error in the diagnose report sent to the server, or display it in the diagnose viewer.

This is a breaking change in how the config is loaded. Communicate this accordingly.

**Comment by tombruijn** [comment]
I like the option/flag to activate the behavior opt-in and make it the default in the next major release. We can't add a CLI option/flag to whatever process starts AppSignal, but we could make it an environment variable like `APPSIGNAL_ON_CONFIG_ERROR=fail`. It wouldn't be a config option for the config file, because this is about the config file itself failing to be parsed.

**Comment by jjb** [comment]
sounds good

FWIW, in my use case, i am happy that I now have tests guarding me against this scenario. so, no need from me at least to build the transitional feature in version 3 as i suggested above.
