### ISSUE TITLE
Feature request: GoodJob integration

### ISSUE THREAD

**Issue by olivier-thatch** [appsignal/appsignal-ruby#960]
[GoodJob](https://github.com/bensheldon/good_job) is an ActiveJob backend, kind of like Sidekiq or Resque. Would you consider adding an integration for it? Or accepting a PR that adds such an integration if I submit one myself?

**Comment by tombruijn** [comment]
We provide support through our active job instrumentation for all adapters. It should report something already for goodjob: errors and performance for the correct job name. Do you see any data for goodjob jobs being reported to AppSignal?

**Comment by tombruijn** [comment]
> errors raised early in the stack are not correctly tagged in the background namespace, e.g. ActiveRecord::ConnectionTimeoutError raised when the cron scheduler fails to check out a connection

That sounds like a bug if it happens. Can you reach out to us on support@appsignal.com with a link to an example trace so we can take a look?

> automated dashboard like one for Sidekiq is missing (the [demo](https://goodjob-demo.herokuapp.com/good_job/jobs) shows what's possible)

We can probably tie this into an ActiveJob dashboard, or is it used without ActiveJob?

**Comment by tombruijn** [comment]
> automated dashboard like one for Sidekiq is missing (the [demo](https://goodjob-demo.herokuapp.com/good_job/jobs) shows what's possible)

@bdewater-thatch we have an automated dashboard for Active Job, is none being added for your app in AppSignal, or are you missing some graphs? It has less graphs I see. Which ones you're missing?
