### ISSUE TITLE
AppSignal Sidekiq probe prematurely creates Redis pool now that Sidekiq creates the pool lazily

### ISSUE THREAD

**Issue by weilandia** [appsignal/appsignal-ruby#962]
## Describe the bug

Related: https://github.com/sidekiq/sidekiq/issues/5897

Ruby version: 3.2
Rails version: edge
AppSignal version: 3.4.1

AppSignal prematurely creates the Sidekiq Redis pool causing this:

Sidekiq 7.x has redis connection log that appears after opening the rails console, with a delay. I wouldn't usually post this as an issue, but many times already it has interfered with something I was already typing in the console:

```
[PRODUCTION] irb(main):001:0> a=ActionMailbox::InboundEmail.find n
[PRODUCTION] irb(main):003:0> 2023-04-26 16:34:00.845433 I [44:99740 redis_connection.rb:15] Sidekiq -- Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://..."}
[PRODUCTION] irb(main):001:0> ...
```

## To Reproduce
- Run a rails app with AppSignal and Sidekiq7, open a console.

**Comment by tombruijn** [comment]
Internal Slack discussion: https://appsignal.slack.com/archives/CNPP953E2/p1682961972167449

**Comment by tombruijn** [comment]
Intercom conversation: https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/all/conversation/16410700207264#part_id=comment-16410700207264-21349872474 (Private link)

**Comment by unflxw** [comment]
Hey @weilandia! Thank you for reporting this issue. AppSignal for Ruby version 3.4.2 was just released, with a fix to the issue you described.
