### ISSUE TITLE
Suggestion to rename Appsignal to AppSignal

### ISSUE THREAD

**Issue by sos4nt** [appsignal/appsignal-ruby#977]
The current module / namespace is spelled `Appsignal`. I would prefer `AppSignal` (with capital "S") for two reasons:

1. it would reflect the spelling of the company's / service's name
2. my IDE (RubyMine) would stop complaining about a misspelled constant

Thanks in advance for considering this change for an upcoming release.

---

Implementation-wise you can add a fallback for backwards compatibility:

```ruby
module AppSignal
  # ...
end
Appsignal = AppSignal
Object.deprecate_constant :Appsignal
```

**Comment by unflxw** [comment]
Hi @sosant!

We're unlikely to do this -- we uniformly use `Appsignal` as the spelling for the top-level module or class in all our integrations.

But of course, in your application, you could do the opposite of what you suggest here, and then use `AppSignal` throughout:

```ruby
AppSignal = Appsignal
```
