### ISSUE TITLE
Basic Rack integration broken? Documentation outdated

### ISSUE THREAD

**Issue by 1st8** [appsignal/appsignal-ruby#99]
Hey,

I am currently in the process of setting Appsignal up in a plain Rack application.
Having done this before, I wanted to use the latest appsignal version this time.
This is when I noticed, that your documentation on http://docs.appsignal.com/getting-started/supported-frameworks.html#rack-other is using the old, now unavailable, `Appsignal::Rack::Listener` and `Appsignal::Rack::Instrumentation` middlewares.

By looking at the source code, I quickly found the potential successor `Appsignal::Rack::StreamingListener`, which I added instead of the middlewares named above.

Now I am facing another problem, my request errors are not being sent to Appsignal, despite having a working configuration (`Appsignal.active?` is true and `Appsignal.send_exception` works).
I even added an error catching middleware AFTER the `Appsignal::Rack::StreamingListener` to confirm my errors are passing through it.
Since my application is in no way delivering a streaming response, I suspect that the middleware is not suited or even broken for my use case.

What do you think?

Cheers
Christoph

**Comment by 1st8** [comment]
I think the problem is rather simple:
When an exception happens in the `@app.call(env)` part, it is added to the transaction as usual.
Since the exception is then re-raised, no `StreamWrapper` instance is returned, and the transaction has thus no way of ever completing.

I think adding something like this after line 38 would solve the problem:

```ruby
Appsignal::Transaction.complete_current! if transaction.has_error?
```

Unfortunately I can't find anything like `Appsignal::Transaction#has_error`, otherwise I would've submitted a PR.

**Comment by thijsc** [comment]
This was an oversight on our part, we removed the Rack listener but have not provided a replacement yet. `Appsignal::Rack::StreamingListener` is intended for situations where you keep a Rack response open for long periods of time. I'll have a look at reinstating the Rack listener later this week.

Is this a custom Rack app? Or do you use a framework we don't support out of the box yet?

**Comment by 1st8** [comment]
Whoops, I forgot about this.
I am using Hanami, formerly Lotus.rb, but a plain Rack middleware is my preferred solution.
The referenced PR #99 resolved my issue and should help making the `StreamingListener` usable for non-streaming use-cases in general. 
Does my explanation above and the referenced solution sense for you?

**Comment by thijsc** [comment]
Thanks for the pull! The streaming listener is intended for situations where you keep a stream open for longer periods of time. I've added a replacement for the old Rack instrumentation in #103. Would that fix your use case?
